local M = {}

function M.get(p)
  return {
    BufferLineFill = { bg = p.bg_dark },
    BufferLineBackground = { fg = p.muted, bg = p.bg },
    BufferLineBuffer = { fg = p.muted, bg = p.bg },
    BufferLineBufferVisible = { fg = p.fg_dim, bg = p.bg },
    BufferLineBufferSelected = { fg = p.fg, bg = p.bg_alt, bold = true },
    BufferLineCloseButton = { fg = p.subtle, bg = p.bg },
    BufferLineCloseButtonVisible = { fg = p.muted, bg = p.bg },
    BufferLineCloseButtonSelected = { fg = p.red, bg = p.bg_alt },
    BufferLineNumbers = { fg = p.subtle, bg = p.bg },
    BufferLineNumbersVisible = { fg = p.muted, bg = p.bg },
    BufferLineNumbersSelected = { fg = p.fg_dim, bg = p.bg_alt, bold = true },
    BufferLineModified = { fg = p.orange, bg = p.bg },
    BufferLineModifiedVisible = { fg = p.orange, bg = p.bg },
    BufferLineModifiedSelected = { fg = p.orange, bg = p.bg_alt },
    BufferLineDuplicate = { fg = p.subtle, bg = p.bg, italic = true },
    BufferLineDuplicateVisible = { fg = p.muted, bg = p.bg, italic = true },
    BufferLineDuplicateSelected = { fg = p.fg_dim, bg = p.bg_alt, italic = true },
    BufferLineSeparator = { fg = p.border, bg = p.bg },
    BufferLineSeparatorVisible = { fg = p.border, bg = p.bg },
    BufferLineSeparatorSelected = { fg = p.border, bg = p.bg_alt },
    BufferLineIndicatorVisible = { fg = p.bg, bg = p.bg },
    BufferLineIndicatorSelected = { fg = p.green, bg = p.bg_alt },
    BufferLinePick = { fg = p.red, bg = p.bg, bold = true },
    BufferLinePickVisible = { fg = p.red, bg = p.bg, bold = true },
    BufferLinePickSelected = { fg = p.red, bg = p.bg_alt, bold = true },
    BufferLineOffset = { fg = p.green, bg = p.bg, bold = true },
    BufferLineOffsetSeparator = { fg = p.border, bg = p.bg },
    BufferLineTab = { fg = p.muted, bg = p.bg },
    BufferLineTabSelected = { fg = p.fg, bg = p.selection, bold = true },
    BufferLineTabClose = { fg = p.red, bg = p.bg },
    BufferLineTabSeparator = { fg = p.border, bg = p.bg },
    BufferLineTabSeparatorSelected = { fg = p.green, bg = p.selection },
    BufferLineDiagnostic = { fg = p.subtle, bg = p.bg },
    BufferLineDiagnosticVisible = { fg = p.muted, bg = p.bg },
    BufferLineDiagnosticSelected = { fg = p.fg_dim, bg = p.bg_alt },
    BufferLineHint = { fg = p.green, bg = p.bg },
    BufferLineHintVisible = { fg = p.green, bg = p.bg },
    BufferLineHintSelected = { fg = p.green, bg = p.bg_alt, bold = true },
    BufferLineHintDiagnostic = { fg = p.green, bg = p.bg },
    BufferLineHintDiagnosticVisible = { fg = p.green, bg = p.bg },
    BufferLineHintDiagnosticSelected = { fg = p.green, bg = p.bg_alt },
    BufferLineInfo = { fg = p.blue, bg = p.bg },
    BufferLineInfoVisible = { fg = p.blue, bg = p.bg },
    BufferLineInfoSelected = { fg = p.blue, bg = p.bg_alt, bold = true },
    BufferLineInfoDiagnostic = { fg = p.blue, bg = p.bg },
    BufferLineInfoDiagnosticVisible = { fg = p.blue, bg = p.bg },
    BufferLineInfoDiagnosticSelected = { fg = p.blue, bg = p.bg_alt },
    BufferLineWarning = { fg = p.orange, bg = p.bg },
    BufferLineWarningVisible = { fg = p.orange, bg = p.bg },
    BufferLineWarningSelected = { fg = p.orange, bg = p.bg_alt, bold = true },
    BufferLineWarningDiagnostic = { fg = p.orange, bg = p.bg },
    BufferLineWarningDiagnosticVisible = { fg = p.orange, bg = p.bg },
    BufferLineWarningDiagnosticSelected = { fg = p.orange, bg = p.bg_alt },
    BufferLineError = { fg = p.red, bg = p.bg },
    BufferLineErrorVisible = { fg = p.red, bg = p.bg },
    BufferLineErrorSelected = { fg = p.red, bg = p.bg_alt, bold = true },
    BufferLineErrorDiagnostic = { fg = p.red, bg = p.bg },
    BufferLineErrorDiagnosticVisible = { fg = p.red, bg = p.bg },
    BufferLineErrorDiagnosticSelected = { fg = p.red, bg = p.bg_alt },
    BufferLineGroupSeparator = { fg = p.border, bg = p.bg },
    BufferLineGroupLabel = { fg = p.green, bg = p.bg_alt, bold = true },
    BufferLineTruncMarker = { fg = p.subtle, bg = p.bg_dark },
    BufferLineMiniIconsAzure = { fg = p.blue, bg = p.bg },
    BufferLineMiniIconsAzureInactive = { fg = p.blue, bg = p.bg },
    BufferLineMiniIconsAzureSelected = { fg = p.blue, bg = p.bg_alt },
    BufferLineMiniIconsBlue = { fg = p.blue, bg = p.bg },
    BufferLineMiniIconsBlueInactive = { fg = p.blue, bg = p.bg },
    BufferLineMiniIconsBlueSelected = { fg = p.blue, bg = p.bg_alt },
    BufferLineMiniIconsCyan = { fg = p.cyan, bg = p.bg },
    BufferLineMiniIconsCyanInactive = { fg = p.cyan, bg = p.bg },
    BufferLineMiniIconsCyanSelected = { fg = p.cyan, bg = p.bg_alt },
    BufferLineMiniIconsGreen = { fg = p.green, bg = p.bg },
    BufferLineMiniIconsGreenInactive = { fg = p.green, bg = p.bg },
    BufferLineMiniIconsGreenSelected = { fg = p.green, bg = p.bg_alt },
    BufferLineMiniIconsGrey = { fg = p.muted, bg = p.bg },
    BufferLineMiniIconsGreyInactive = { fg = p.muted, bg = p.bg },
    BufferLineMiniIconsGreySelected = { fg = p.muted, bg = p.bg_alt },
    BufferLineMiniIconsOrange = { fg = p.orange, bg = p.bg },
    BufferLineMiniIconsOrangeInactive = { fg = p.orange, bg = p.bg },
    BufferLineMiniIconsOrangeSelected = { fg = p.orange, bg = p.bg_alt },
    BufferLineMiniIconsPurple = { fg = p.magenta, bg = p.bg },
    BufferLineMiniIconsPurpleInactive = { fg = p.magenta, bg = p.bg },
    BufferLineMiniIconsPurpleSelected = { fg = p.magenta, bg = p.bg_alt },
    BufferLineMiniIconsRed = { fg = p.red, bg = p.bg },
    BufferLineMiniIconsRedInactive = { fg = p.red, bg = p.bg },
    BufferLineMiniIconsRedSelected = { fg = p.red, bg = p.bg_alt },
    BufferLineMiniIconsYellow = { fg = p.yellow, bg = p.bg },
    BufferLineMiniIconsYellowInactive = { fg = p.yellow, bg = p.bg },
    BufferLineMiniIconsYellowSelected = { fg = p.yellow, bg = p.bg_alt },
  }
end

return M
