local M = {}

function M.get(p)
  return {
    BlinkCmpLabel = { fg = p.fg },
    BlinkCmpLabelMatch = { fg = p.orange, bold = true },
    BlinkCmpLabelDeprecated = { fg = p.subtle, strikethrough = true },
    BlinkCmpLabelDetail = { fg = p.muted },
    BlinkCmpLabelDescription = { fg = p.comment },
    BlinkCmpSource = { fg = p.muted },
    BlinkCmpKind = { fg = p.blue },
    BlinkCmpKindText = { fg = p.fg },
    BlinkCmpKindMethod = { fg = p.entity },
    BlinkCmpKindFunction = { fg = p.entity },
    BlinkCmpKindConstructor = { fg = p.class },
    BlinkCmpKindField = { fg = p.property },
    BlinkCmpKindVariable = { fg = p.variable },
    BlinkCmpKindClass = { fg = p.class },
    BlinkCmpKindInterface = { fg = p.interface },
    BlinkCmpKindModule = { fg = p.namespace },
    BlinkCmpKindProperty = { fg = p.property },
    BlinkCmpKindUnit = { fg = p.number },
    BlinkCmpKindValue = { fg = p.constant },
    BlinkCmpKindEnum = { fg = p.class },
    BlinkCmpKindKeyword = { fg = p.keyword, italic = true },
    BlinkCmpKindSnippet = { fg = p.magenta },
    BlinkCmpKindColor = { fg = p.cyan },
    BlinkCmpKindFile = { fg = p.blue },
    BlinkCmpKindReference = { fg = p.link },
    BlinkCmpKindFolder = { fg = p.green },
    BlinkCmpKindEnumMember = { fg = p.constant },
    BlinkCmpKindConstant = { fg = p.constant },
    BlinkCmpKindStruct = { fg = p.class },
    BlinkCmpKindEvent = { fg = p.orange },
    BlinkCmpKindOperator = { fg = p.operator },
    BlinkCmpKindTypeParameter = { fg = p.primitive },
    BlinkCmpScrollBarThumb = { bg = p.subtle },
    BlinkCmpScrollBarGutter = { bg = p.bg_alt },
    BlinkCmpGhostText = { fg = p.subtle },
    BlinkCmpMenu = { fg = p.fg, bg = p.bg_alt },
    BlinkCmpMenuBorder = { fg = p.border, bg = p.bg_alt },
    BlinkCmpMenuSelection = { fg = p.fg, bg = p.selection },
    BlinkCmpDoc = { fg = p.fg, bg = p.bg },
    BlinkCmpDocBorder = { fg = p.border, bg = p.bg },
    BlinkCmpDocSeparator = { fg = p.border, bg = p.bg },
    BlinkCmpDocCursorLine = { bg = p.bg_alt },
    BlinkCmpSignatureHelp = { fg = p.fg, bg = p.bg },
    BlinkCmpSignatureHelpBorder = { fg = p.border, bg = p.bg },
    BlinkCmpSignatureHelpActiveParameter = { fg = p.orange, bold = true },
  }
end

return M
