local M = {}

function M.get(p)
  return {
    GitSignsAdd = { fg = p.diff_add_fg },
    GitSignsChange = { fg = p.diff_change_fg },
    GitSignsDelete = { fg = p.diff_delete_fg },
    GitSignsChangedelete = { fg = p.diff_change_fg },
    GitSignsTopdelete = { fg = p.diff_delete_fg },
    GitSignsUntracked = { fg = p.orange },
    GitSignsAddNr = { fg = p.diff_add_fg },
    GitSignsChangeNr = { fg = p.diff_change_fg },
    GitSignsDeleteNr = { fg = p.diff_delete_fg },
    GitSignsChangedeleteNr = { fg = p.diff_change_fg },
    GitSignsTopdeleteNr = { fg = p.diff_delete_fg },
    GitSignsUntrackedNr = { fg = p.orange },
    GitSignsAddLn = { bg = p.diff_add_bg },
    GitSignsChangeLn = { bg = p.diff_change_bg },
    GitSignsChangedeleteLn = { bg = p.diff_change_bg },
    GitSignsTopdeleteLn = { bg = p.diff_delete_bg },
    GitSignsUntrackedLn = { bg = p.bg_alt },
    GitSignsAddCul = { fg = p.diff_add_fg, bg = p.bg_alt },
    GitSignsChangeCul = { fg = p.diff_change_fg, bg = p.bg_alt },
    GitSignsDeleteCul = { fg = p.diff_delete_fg, bg = p.bg_alt },
    GitSignsChangedeleteCul = { fg = p.diff_change_fg, bg = p.bg_alt },
    GitSignsTopdeleteCul = { fg = p.diff_delete_fg, bg = p.bg_alt },
    GitSignsUntrackedCul = { fg = p.orange, bg = p.bg_alt },
    GitSignsStagedAdd = { fg = p.green },
    GitSignsStagedChange = { fg = p.yellow },
    GitSignsStagedDelete = { fg = p.red },
    GitSignsStagedChangedelete = { fg = p.yellow },
    GitSignsStagedTopdelete = { fg = p.red },
    GitSignsStagedUntracked = { fg = p.orange },
    GitSignsAddPreview = { fg = p.diff_add_fg, bg = p.diff_add_bg },
    GitSignsDeletePreview = { fg = p.diff_delete_fg, bg = p.diff_delete_bg },
    GitSignsNoEOLPreview = { fg = p.orange },
    GitSignsAddInline = { bg = p.diff_add_bg },
    GitSignsDeleteInline = { bg = p.diff_delete_bg },
    GitSignsChangeInline = { bg = p.diff_change_bg },
    GitSignsAddLnInline = { bg = p.diff_add_bg },
    GitSignsChangeLnInline = { bg = p.diff_change_bg },
    GitSignsDeleteLnInline = { bg = p.diff_delete_bg },
    GitSignsDeleteVirtLn = { fg = p.diff_delete_fg, bg = p.diff_delete_bg },
    GitSignsDeleteVirtLnInLine = { fg = p.diff_delete_fg, bg = p.bg_alt },
    GitSignsVirtLnum = { fg = p.subtle },
    GitSignsCurrentLineBlame = { fg = p.subtle, italic = true },
  }
end

return M
