local M = {}

function M.get(p)
  return {
    MiniStatuslineModeNormal = { fg = p.bg_dark, bg = p.green, bold = true },
    MiniStatuslineModeInsert = { fg = p.bg_dark, bg = p.blue, bold = true },
    MiniStatuslineModeVisual = { fg = p.bg_dark, bg = p.magenta, bold = true },
    MiniStatuslineModeReplace = { fg = p.bg_dark, bg = p.red, bold = true },
    MiniStatuslineModeCommand = { fg = p.bg_dark, bg = p.yellow, bold = true },
    MiniStatuslineModeOther = { fg = p.bg_dark, bg = p.cyan, bold = true },
    MiniStatuslineDevinfo = { fg = p.fg_dim, bg = p.bg_dark },
    MiniStatuslineFileinfo = { fg = p.fg_dim, bg = p.bg_dark },
    MiniStatuslineInactive = { fg = p.subtle, bg = p.bg_dark },
    MiniTablineCurrent = { fg = p.fg, bg = p.bg_alt, bold = true },
    MiniTablineVisible = { fg = p.fg_dim, bg = p.bg_dark },
    MiniTablineHidden = { fg = p.muted, bg = p.bg_dark },
    MiniTablineModifiedCurrent = { fg = p.orange, bg = p.bg_alt, bold = true, italic = true },
    MiniTablineModifiedVisible = { fg = p.orange, bg = p.bg_dark, italic = true },
    MiniTablineModifiedHidden = { fg = p.muted, bg = p.bg_dark, italic = true },
    MiniTablineFill = { fg = p.subtle, bg = p.bg_dark },
    MiniTablineTabpagesection = { fg = p.bg_dark, bg = p.green, bold = true },
    MiniTablineTrunc = { fg = p.subtle, bg = p.bg_dark },
    MiniClueBorder = { fg = p.border, bg = p.bg_alt },
    MiniClueDescGroup = { fg = p.green, bold = true },
    MiniClueDescSingle = { fg = p.fg_dim },
    MiniClueNextKey = { fg = p.orange, bold = true },
    MiniClueNextKeyWithPostkeys = { fg = p.yellow, bold = true },
    MiniClueSeparator = { fg = p.subtle },
    MiniClueTitle = { fg = p.blue, bold = true },
    MiniHipatternsFixme = { fg = p.bg, bg = p.red, bold = true },
    MiniHipatternsHack = { fg = p.bg, bg = p.orange, bold = true },
    MiniHipatternsNote = { fg = p.bg, bg = p.blue, bold = true },
    MiniHipatternsTodo = { fg = p.bg, bg = p.yellow, bold = true },
    MiniIconsAzure = { fg = p.blue },
    MiniIconsBlue = { fg = p.blue },
    MiniIconsCyan = { fg = p.cyan },
    MiniIconsGreen = { fg = p.green },
    MiniIconsGrey = { fg = p.muted },
    MiniIconsOrange = { fg = p.orange },
    MiniIconsPurple = { fg = p.magenta },
    MiniIconsRed = { fg = p.red },
    MiniIconsYellow = { fg = p.yellow },
  }
end

return M
