local M = {}

function M.get(p)
  return {
    NoiceCmdline = { fg = p.fg, bg = p.bg_dark },
    NoiceCmdlineIcon = { fg = p.blue },
    NoiceCmdlineIconSearch = { fg = p.yellow },
    NoiceCmdlinePrompt = { fg = p.green, bold = true },
    NoiceCmdlinePopup = { fg = p.fg, bg = p.bg_alt },
    NoiceCmdlinePopupBorder = { fg = p.blue, bg = p.bg_alt },
    NoiceCmdlinePopupTitle = { fg = p.blue, bg = p.bg_alt, bold = true },
    NoiceCmdlinePopupBorderSearch = { fg = p.yellow, bg = p.bg_alt },
    NoiceConfirm = { fg = p.fg, bg = p.bg_alt },
    NoiceConfirmBorder = { fg = p.blue, bg = p.bg_alt },
    NoiceCursor = { fg = p.bg, bg = p.fg },
    NoiceMini = { fg = p.fg_dim, bg = p.bg_dark },
    NoicePopup = { fg = p.fg, bg = p.bg },
    NoicePopupBorder = { link = "FloatBorder" },
    NoicePopupmenu = { fg = p.fg, bg = p.bg_alt },
    NoicePopupmenuMatch = { fg = p.orange, bold = true },
    NoicePopupmenuSelected = { fg = p.fg, bg = p.selection },
    NoiceSplit = { fg = p.fg, bg = p.bg },
    NoiceVirtualText = { fg = p.blue },
    NoiceFormatProgressDone = { fg = p.green, bg = p.bg_alt },
    NoiceFormatProgressTodo = { fg = p.subtle, bg = p.bg_alt },
    NoiceFormatEvent = { fg = p.magenta },
    NoiceFormatKind = { fg = p.orange },
    NoiceFormatDate = { fg = p.muted },
    NoiceFormatConfirm = { fg = p.green },
    NoiceFormatConfirmDefault = { fg = p.green, bold = true },
    NoiceFormatTitle = { fg = p.green, bold = true },
    NoiceFormatLevelDebug = { fg = p.magenta },
    NoiceFormatLevelTrace = { fg = p.muted },
    NoiceFormatLevelOff = { fg = p.subtle },
    NoiceFormatLevelInfo = { fg = p.blue },
    NoiceFormatLevelWarn = { fg = p.orange },
    NoiceFormatLevelError = { fg = p.red, bg = p.bg_dark },
    NoiceLspProgressSpinner = { fg = p.cyan },
    NoiceLspProgressTitle = { fg = p.fg },
    NoiceLspProgressClient = { fg = p.muted },
    NoiceCompletionItemMenu = { fg = p.muted },
    NoiceCompletionItemWord = { fg = p.fg },
    NoiceCompletionItemKindDefault = { fg = p.blue },
    NoiceCompletionItemKindColor = { fg = p.cyan },
    NoiceCompletionItemKindFunction = { fg = p.entity },
    NoiceCompletionItemKindClass = { fg = p.class },
    NoiceCompletionItemKindMethod = { fg = p.entity },
    NoiceCompletionItemKindConstructor = { fg = p.class },
    NoiceCompletionItemKindInterface = { fg = p.interface },
    NoiceCompletionItemKindModule = { fg = p.namespace },
    NoiceCompletionItemKindStruct = { fg = p.class },
    NoiceCompletionItemKindKeyword = { fg = p.keyword, italic = true },
    NoiceCompletionItemKindValue = { fg = p.constant },
    NoiceCompletionItemKindProperty = { fg = p.property },
    NoiceCompletionItemKindConstant = { fg = p.constant },
    NoiceCompletionItemKindSnippet = { fg = p.magenta },
    NoiceCompletionItemKindFolder = { fg = p.green },
    NoiceCompletionItemKindText = { fg = p.fg },
    NoiceCompletionItemKindEnumMember = { fg = p.constant },
    NoiceCompletionItemKindUnit = { fg = p.number },
    NoiceCompletionItemKindField = { fg = p.property },
    NoiceCompletionItemKindFile = { fg = p.blue },
    NoiceCompletionItemKindVariable = { fg = p.variable },
    NoiceCompletionItemKindEnum = { fg = p.class },
    NoiceHiddenCursor = { blend = 100, nocombine = true },
  }
end

return M
