local M = {}
local styles = require("colors.undefined.styles")

function M.get(p)
  local s = styles.get(p)

  local groups = {
    SnacksNormal = s.float.normal,
    SnacksNormalNC = s.float.normal_nc,
    SnacksWinBar = styles.extend(s.popup_editor.title, { fg = p.fg }),
    SnacksWinBarNC = { fg = p.muted, bg = s.popup_editor.normal.bg },
    SnacksTitle = s.popup_editor.title,
    SnacksFooter = s.dim,
    SnacksFooterKey = s.key,
    SnacksFooterDesc = s.muted,
    SnacksBackdrop = s.float.backdrop,
    SnacksWinSeparator = s.float.separator,
    SnacksWinKey = s.key,
    SnacksWinKeySep = s.separator,
    SnacksWinKeyDesc = s.dim,

    SnacksPicker = s.popup_editor.normal,
    SnacksPickerBox = s.popup_editor.normal,
    SnacksPickerBoxBorder = s.popup_editor.border,
    SnacksPickerBoxTitle = s.popup_editor.title,
    SnacksPickerBorder = s.popup_editor.border,
    SnacksPickerTitle = s.popup_editor.title,
    SnacksPickerCursorLine = s.popup.selected,
    SnacksPickerInput = s.popup_editor.normal,
    SnacksPickerInputBorder = s.popup_editor.border,
    SnacksPickerInputTitle = s.popup_editor.title,
    SnacksPickerList = s.popup_editor.normal,
    SnacksPickerListBorder = s.popup_editor.border,
    SnacksPickerListCursorLine = s.popup.selected,
    SnacksPickerListTitle = s.popup_editor.title,
    SnacksPickerPreview = s.popup_editor.normal,
    SnacksPickerPreviewBorder = s.popup_editor.border,
    SnacksPickerPreviewTitle = s.popup_editor.title,
    SnacksPickerMatch = s.match,
    SnacksPickerSearch = { fg = p.bg, bg = p.yellow },
    SnacksPickerPrompt = s.input.prompt,
    SnacksPickerInputSearch = { fg = p.yellow },
    SnacksPickerSpecial = { fg = p.support },
    SnacksPickerLabel = { fg = p.property },
    SnacksPickerTotals = s.muted,
    SnacksPickerFile = { fg = p.fg },
    SnacksPickerLink = s.url,
    SnacksPickerLinkBroken = { fg = p.red, underline = true },
    SnacksPickerDirectory = { fg = p.green },
    SnacksPickerPathIgnored = s.subtle,
    SnacksPickerPathHidden = s.muted,
    SnacksPickerDir = { fg = p.green },
    SnacksPickerToggle = { fg = p.orange },
    SnacksPickerDimmed = s.subtle,
    SnacksPickerRow = { fg = p.number },
    SnacksPickerCol = { fg = p.number },
    SnacksPickerComment = s.syntax.comment,
    SnacksPickerDesc = s.dim,
    SnacksPickerDelim = { fg = p.delimiter },
    SnacksPickerSpinner = { fg = p.cyan },
    SnacksPickerSelected = { fg = p.green, bold = true },
    SnacksPickerCmd = { fg = p.entity },
    SnacksPickerCmdBuiltin = { fg = p.support },
    SnacksPickerUnselected = s.subtle,
    SnacksPickerIdx = s.muted,
    SnacksPickerBold = { fg = p.fg, bold = true },
    SnacksPickerTree = s.subtle,
    SnacksPickerItalic = { fg = p.fg_dim, italic = true },
    SnacksPickerCode = s.syntax.string,
    SnacksPickerAuPattern = s.syntax.string,
    SnacksPickerAuEvent = s.syntax.keyword,
    SnacksPickerAuGroup = { fg = p.namespace },
    SnacksPickerDiagnosticCode = s.muted,
    SnacksPickerDiagnosticSource = { fg = p.comment },
    SnacksPickerRegister = { fg = p.orange },
    SnacksPickerKeymapMode = { fg = p.magenta },
    SnacksPickerKeymapLhs = s.key,
    SnacksPickerKeymapNowait = { fg = p.orange },
    SnacksPickerKeymapRhs = s.dim,
    SnacksPickerBufNr = { fg = p.number },
    SnacksPickerBufFlags = { fg = p.orange },
    SnacksPickerBufType = { fg = p.interface },
    SnacksPickerFileType = { fg = p.primitive },
    SnacksPickerTime = s.muted,
    SnacksPickerUndoAdded = s.diff.add,
    SnacksPickerUndoRemoved = s.diff.delete,
    SnacksPickerUndoCurrent = { fg = p.yellow, bold = true },
    SnacksPickerUndoSaved = { fg = p.green },
    SnacksPickerGitCommit = { fg = p.yellow },
    SnacksPickerGitBreaking = { fg = p.red, bold = true },
    SnacksPickerGitDetached = { fg = p.orange },
    SnacksPickerGitBranch = { fg = p.green },
    SnacksPickerGitBranchCurrent = { fg = p.green, bold = true },
    SnacksPickerGitDate = s.muted,
    SnacksPickerGitIssue = { fg = p.link },
    SnacksPickerGitAuthor = { fg = p.attribute },
    SnacksPickerGitType = { fg = p.magenta },
    SnacksPickerGitScope = { fg = p.namespace },
    SnacksPickerGitStatus = s.muted,
    SnacksPickerGitStatusAdded = s.diff.add,
    SnacksPickerGitStatusModified = s.diff.change,
    SnacksPickerGitStatusDeleted = s.diff.delete,
    SnacksPickerGitStatusRenamed = { fg = p.cyan },
    SnacksPickerGitStatusCopied = { fg = p.cyan },
    SnacksPickerGitStatusUntracked = { fg = p.orange },
    SnacksPickerGitStatusIgnored = s.subtle,
    SnacksPickerGitStatusUnmerged = { fg = p.red },
    SnacksPickerGitStatusStaged = { fg = p.green, bold = true },
    SnacksPickerManSection = { fg = p.magenta },
    SnacksPickerPickWin = { fg = p.bg, bg = p.yellow, bold = true },
    SnacksPickerPickWinCurrent = { fg = p.bg, bg = p.green, bold = true },
    SnacksPickerLspDisabled = s.subtle,
    SnacksPickerLspEnabled = { fg = p.green },
    SnacksPickerLspAttached = { fg = p.green },
    SnacksPickerLspAttachedBuf = { fg = p.cyan },
    SnacksPickerLspUnavailable = { fg = p.red },
    SnacksPickerManPage = { fg = p.fg },
    SnacksPickerIcon = { fg = p.green },
    SnacksPickerIconSource = s.muted,
    SnacksPickerIconName = { fg = p.fg },
    SnacksPickerIconCategory = { fg = p.magenta },
    SnacksPickerIconArray = s.kind.array,
    SnacksPickerIconBoolean = s.kind.boolean,
    SnacksPickerIconClass = s.kind.class,
    SnacksPickerIconConstant = s.kind.constant,
    SnacksPickerIconConstructor = s.kind.constructor,
    SnacksPickerIconEnum = s.kind.enum,
    SnacksPickerIconEnumMember = s.kind.enum_member,
    SnacksPickerIconEvent = s.kind.event,
    SnacksPickerIconField = s.kind.field,
    SnacksPickerIconFile = s.kind.file,
    SnacksPickerIconFunction = s.kind.function_,
    SnacksPickerIconInterface = s.kind.interface,
    SnacksPickerIconKey = s.kind.key,
    SnacksPickerIconMethod = s.kind.method,
    SnacksPickerIconModule = s.kind.module,
    SnacksPickerIconNamespace = s.kind.namespace,
    SnacksPickerIconNull = s.kind.null,
    SnacksPickerIconNumber = s.kind.number,
    SnacksPickerIconObject = s.kind.object,
    SnacksPickerIconOperator = s.kind.operator,
    SnacksPickerIconPackage = s.kind.package,
    SnacksPickerIconProperty = s.kind.property,
    SnacksPickerIconString = s.syntax.string,
    SnacksPickerIconStruct = s.kind.struct,
    SnacksPickerIconTypeParameter = s.kind.type_parameter,
    SnacksPickerIconVariable = s.kind.variable,
    SnacksPickerRule = { fg = p.border },
    SnacksDiffHeader = { fg = p.fg_dim, bg = p.bg_alt },
    SnacksDiffLabel = { fg = p.property, bg = p.bg_alt, bold = true },

    SnacksDashboardNormal = s.float.normal,
    SnacksDashboardTerminal = { fg = p.green },
    SnacksDashboardHeader = s.title,
    SnacksDashboardFooter = s.dim,
    SnacksDashboardIcon = { fg = p.green },
    SnacksDashboardKey = s.key,
    SnacksDashboardDesc = s.dim,
    SnacksNotifierHistory = s.float.normal,
    SnacksNotifierHistoryTitle = s.title,
    SnacksNotifierHistoryDateTime = s.muted,
    SnacksNotifierMinimal = s.float.normal,
    SnacksIndent = { fg = p.whitespace },
    SnacksIndentScope = { fg = p.yellow },
    SnacksIndentChunk = { fg = p.border },
    SnacksIndentBlank = { fg = p.bg_alt },
    SnacksIndent1 = { fg = p.red },
    SnacksIndent2 = { fg = p.orange },
    SnacksIndent3 = { fg = p.yellow },
    SnacksIndent4 = { fg = p.green },
    SnacksIndent5 = { fg = p.cyan },
    SnacksIndent6 = { fg = p.blue },
    SnacksIndent7 = { fg = p.magenta },
    SnacksIndent8 = { fg = p.muted },
    SnacksInputIcon = { fg = p.green },
    SnacksInputNormal = s.input_editor.normal,
    SnacksInputBorder = s.input_editor.border,
    SnacksInputTitle = s.input_editor.title,
    SnacksInputPrompt = s.input.prompt,
    SnacksStatusColumnMark = { fg = p.yellow, bold = true },
  }

  local notifier_levels = {
    Info = p.blue,
    Warn = p.orange,
    Error = p.red,
    Debug = p.magenta,
    Trace = p.muted,
  }

  for level, color in pairs(notifier_levels) do
    groups["SnacksNotifier" .. level] = { fg = color, bg = p.bg }
    groups["SnacksNotifierIcon" .. level] = { fg = color, bg = p.bg }
    groups["SnacksNotifierBorder" .. level] = { fg = color, bg = p.bg }
    groups["SnacksNotifierTitle" .. level] = { fg = color, bg = p.bg, bold = true }
    groups["SnacksNotifierFooter" .. level] = { fg = color, bg = p.bg }
  end

  return groups
end

return M
