local M = {}

function M.get(p)
  return {
    SnacksNormal = { fg = p.fg, bg = p.bg },
    SnacksNormalNC = { fg = p.fg_dim, bg = p.bg },
    SnacksWinBar = { fg = p.fg, bg = p.bg_alt, bold = true },
    SnacksWinBarNC = { fg = p.muted, bg = p.bg_alt },
    SnacksTitle = { fg = p.green, bold = true },
    SnacksFooter = { fg = p.fg_dim },
    SnacksFooterKey = { fg = p.orange, bold = true },
    SnacksFooterDesc = { fg = p.muted },
    SnacksBackdrop = { bg = p.bg_dark },
    SnacksWinSeparator = { fg = p.border, bg = p.bg },
    SnacksWinKey = { fg = p.orange, bold = true },
    SnacksWinKeySep = { fg = p.subtle },
    SnacksWinKeyDesc = { fg = p.fg_dim },

    SnacksPickerMatch = { fg = p.orange, bold = true },
    SnacksPickerSearch = { fg = p.bg, bg = p.yellow },
    SnacksPickerPrompt = { fg = p.green, bold = true },
    SnacksPickerInputSearch = { fg = p.yellow },
    SnacksPickerSpecial = { fg = p.support },
    SnacksPickerLabel = { fg = p.property },
    SnacksPickerTotals = { fg = p.muted },
    SnacksPickerFile = { fg = p.fg },
    SnacksPickerLink = { fg = p.link, underline = true },
    SnacksPickerLinkBroken = { fg = p.red, underline = true },
    SnacksPickerDirectory = { fg = p.green },
    SnacksPickerPathIgnored = { fg = p.subtle },
    SnacksPickerPathHidden = { fg = p.muted },
    SnacksPickerDir = { fg = p.green },
    SnacksPickerToggle = { fg = p.orange },
    SnacksPickerDimmed = { fg = p.subtle },
    SnacksPickerRow = { fg = p.number },
    SnacksPickerCol = { fg = p.number },
    SnacksPickerComment = { fg = p.comment, italic = true },
    SnacksPickerDesc = { fg = p.fg_dim },
    SnacksPickerDelim = { fg = p.delimiter },
    SnacksPickerSpinner = { fg = p.cyan },
    SnacksPickerSelected = { fg = p.green, bold = true },
    SnacksPickerCmd = { fg = p.entity },
    SnacksPickerCmdBuiltin = { fg = p.support },
    SnacksPickerUnselected = { fg = p.subtle },
    SnacksPickerIdx = { fg = p.muted },
    SnacksPickerBold = { fg = p.fg, bold = true },
    SnacksPickerTree = { fg = p.subtle },
    SnacksPickerItalic = { fg = p.fg_dim, italic = true },
    SnacksPickerCode = { fg = p.string },
    SnacksPickerAuPattern = { fg = p.string },
    SnacksPickerAuEvent = { fg = p.keyword, italic = true },
    SnacksPickerAuGroup = { fg = p.namespace },
    SnacksPickerDiagnosticCode = { fg = p.muted },
    SnacksPickerDiagnosticSource = { fg = p.comment },
    SnacksPickerRegister = { fg = p.orange },
    SnacksPickerKeymapMode = { fg = p.magenta },
    SnacksPickerKeymapLhs = { fg = p.green },
    SnacksPickerKeymapNowait = { fg = p.orange },
    SnacksPickerKeymapRhs = { fg = p.fg_dim },
    SnacksPickerBufNr = { fg = p.number },
    SnacksPickerBufFlags = { fg = p.orange },
    SnacksPickerBufType = { fg = p.interface },
    SnacksPickerFileType = { fg = p.primitive },
    SnacksPickerTime = { fg = p.muted },
    SnacksPickerUndoAdded = { fg = p.diff_add_fg },
    SnacksPickerUndoRemoved = { fg = p.diff_delete_fg },
    SnacksPickerUndoCurrent = { fg = p.yellow, bold = true },
    SnacksPickerUndoSaved = { fg = p.green },
    SnacksPickerGitCommit = { fg = p.yellow },
    SnacksPickerGitBreaking = { fg = p.red, bold = true },
    SnacksPickerGitDetached = { fg = p.orange },
    SnacksPickerGitBranch = { fg = p.green },
    SnacksPickerGitBranchCurrent = { fg = p.green, bold = true },
    SnacksPickerGitDate = { fg = p.muted },
    SnacksPickerGitIssue = { fg = p.blue },
    SnacksPickerGitAuthor = { fg = p.attribute },
    SnacksPickerGitType = { fg = p.magenta },
    SnacksPickerGitScope = { fg = p.namespace },
    SnacksPickerGitStatus = { fg = p.muted },
    SnacksPickerGitStatusAdded = { fg = p.diff_add_fg },
    SnacksPickerGitStatusModified = { fg = p.diff_change_fg },
    SnacksPickerGitStatusDeleted = { fg = p.diff_delete_fg },
    SnacksPickerGitStatusRenamed = { fg = p.blue },
    SnacksPickerGitStatusCopied = { fg = p.cyan },
    SnacksPickerGitStatusUntracked = { fg = p.orange },
    SnacksPickerGitStatusIgnored = { fg = p.subtle },
    SnacksPickerGitStatusUnmerged = { fg = p.red },
    SnacksPickerGitStatusStaged = { fg = p.green, bold = true },
    SnacksPickerManSection = { fg = p.magenta },
    SnacksPickerPickWin = { fg = p.bg, bg = p.yellow, bold = true },
    SnacksPickerPickWinCurrent = { fg = p.bg, bg = p.green, bold = true },
    SnacksPickerLspDisabled = { fg = p.subtle },
    SnacksPickerLspEnabled = { fg = p.green },
    SnacksPickerLspAttached = { fg = p.blue },
    SnacksPickerLspAttachedBuf = { fg = p.cyan },
    SnacksPickerLspUnavailable = { fg = p.red },
    SnacksPickerManPage = { fg = p.fg },
    SnacksPickerIcon = { fg = p.blue },
    SnacksPickerIconSource = { fg = p.muted },
    SnacksPickerIconName = { fg = p.fg },
    SnacksPickerIconCategory = { fg = p.magenta },
    SnacksPickerIconArray = { fg = p.orange },
    SnacksPickerIconBoolean = { fg = p.boolean },
    SnacksPickerIconClass = { fg = p.class },
    SnacksPickerIconConstant = { fg = p.constant },
    SnacksPickerIconConstructor = { fg = p.class },
    SnacksPickerIconEnum = { fg = p.class },
    SnacksPickerIconEnumMember = { fg = p.constant },
    SnacksPickerIconEvent = { fg = p.orange },
    SnacksPickerIconField = { fg = p.property },
    SnacksPickerIconFile = { fg = p.blue },
    SnacksPickerIconFunction = { fg = p.entity },
    SnacksPickerIconInterface = { fg = p.interface },
    SnacksPickerIconKey = { fg = p.property },
    SnacksPickerIconMethod = { fg = p.entity },
    SnacksPickerIconModule = { fg = p.namespace },
    SnacksPickerIconNamespace = { fg = p.namespace },
    SnacksPickerIconNull = { fg = p.muted },
    SnacksPickerIconNumber = { fg = p.number },
    SnacksPickerIconObject = { fg = p.primitive },
    SnacksPickerIconOperator = { fg = p.operator },
    SnacksPickerIconPackage = { fg = p.namespace },
    SnacksPickerIconProperty = { fg = p.property },
    SnacksPickerIconString = { fg = p.string },
    SnacksPickerIconStruct = { fg = p.class },
    SnacksPickerIconTypeParameter = { fg = p.primitive },
    SnacksPickerIconVariable = { fg = p.variable },
    SnacksPickerRule = { fg = p.border },

    SnacksDashboardNormal = { fg = p.fg, bg = p.bg },
    SnacksDashboardTerminal = { fg = p.green },
    SnacksDashboardHeader = { fg = p.green, bold = true },
    SnacksDashboardFooter = { fg = p.fg_dim },
    SnacksDashboardIcon = { fg = p.blue },
    SnacksDashboardKey = { fg = p.orange, bold = true },
    SnacksDashboardDesc = { fg = p.fg_dim },
    SnacksNotifierInfo = { fg = p.blue },
    SnacksNotifierWarn = { fg = p.orange },
    SnacksNotifierError = { fg = p.red },
    SnacksNotifierDebug = { fg = p.magenta },
    SnacksNotifierTrace = { fg = p.muted },
    SnacksNotifierIconInfo = { fg = p.blue },
    SnacksNotifierIconWarn = { fg = p.orange },
    SnacksNotifierIconError = { fg = p.red },
    SnacksNotifierIconDebug = { fg = p.magenta },
    SnacksNotifierIconTrace = { fg = p.muted },
    SnacksNotifierBorderInfo = { fg = p.blue },
    SnacksNotifierBorderWarn = { fg = p.orange },
    SnacksNotifierBorderError = { fg = p.red },
    SnacksNotifierBorderDebug = { fg = p.magenta },
    SnacksNotifierBorderTrace = { fg = p.muted },
    SnacksNotifierTitleInfo = { fg = p.blue, bold = true },
    SnacksNotifierTitleWarn = { fg = p.orange, bold = true },
    SnacksNotifierTitleError = { fg = p.red, bold = true },
    SnacksNotifierTitleDebug = { fg = p.magenta, bold = true },
    SnacksNotifierTitleTrace = { fg = p.muted, bold = true },
    SnacksNotifierFooterInfo = { fg = p.blue },
    SnacksNotifierFooterWarn = { fg = p.orange },
    SnacksNotifierFooterError = { fg = p.red },
    SnacksNotifierFooterDebug = { fg = p.magenta },
    SnacksNotifierFooterTrace = { fg = p.muted },
    SnacksNotifierHistory = { fg = p.fg, bg = p.bg },
    SnacksNotifierHistoryTitle = { fg = p.green, bold = true },
    SnacksNotifierHistoryDateTime = { fg = p.muted },
    SnacksNotifierMinimal = { fg = p.fg, bg = p.bg },
    SnacksIndent = { fg = p.whitespace },
    SnacksIndentScope = { fg = p.yellow },
    SnacksIndentChunk = { fg = p.border },
    SnacksIndentBlank = { fg = p.bg_alt },
    SnacksIndent1 = { fg = p.red },
    SnacksIndent2 = { fg = p.orange },
    SnacksIndent3 = { fg = p.yellow },
    SnacksIndent4 = { fg = p.green },
    SnacksIndent5 = { fg = p.cyan },
    SnacksIndent6 = { fg = p.blue },
    SnacksIndent7 = { fg = p.magenta },
    SnacksIndent8 = { fg = p.muted },
    SnacksInputIcon = { fg = p.green },
    SnacksInputNormal = { fg = p.fg, bg = p.bg_alt },
    SnacksInputBorder = { fg = p.blue, bg = p.bg_alt },
    SnacksInputTitle = { fg = p.blue, bg = p.bg_alt, bold = true },
    SnacksInputPrompt = { fg = p.green },
    SnacksStatusColumnMark = { fg = p.yellow, bold = true },
  }
end

return M
