local palette = {
  fg = "#dbd7ca",
  fg_dim = "#a8a29e",
  muted = "#959da5",
  subtle = "#6a737d",
  bg = "#262626",
  bg_alt = "#292929",
  bg_dark = "#212221",
  border = "#4a4a4a",
  selection = "#3a3a3a",
  inactive_selection = "#303030",
  whitespace = "#383838",

  red = "#cb7676",
  orange = "#d4976c",
  yellow = "#e6cc77",
  green = "#4d9375",
  cyan = "#06b6d4",
  blue = "#6394bf",
  magenta = "#d9739f",

  comment = "#758575",
  delimiter = "#929292",
  constant = "#c99076",
  entity = "#80a665",
  tag = "#4d9375",
  keyword = "#4d9375",
  storage = "#cb7676",
  string = "#c98a7d",
  support = "#b8a965",
  property = "#b8a965",
  attribute = "#bd976a",
  variable = "#bd976a",
  primitive = "#5DA994",
  namespace = "#db889a",
  operator = "#cb7676",
  regexp = "#c4704f",
  number = "#4C9A91",
  boolean = "#4d9375",
  invalid = "#fdaeb7",
  class = "#6872ab",
  interface = "#5d99a9",
  link = "#4d9375", -- same as green, used for underlined text like markdown links

  diff_delete_fg = "#fdaeb7",
  diff_delete_bg = "#3f3335",
  diff_add_fg = "#85e89d",
  diff_add_bg = "#2f3f34",
  diff_change_fg = "#e6cc77",
  diff_change_bg = "#343126",
  diff_text_bg = "#4a402b",
  diff_header = "#79b8ff",

  markdown_heading_bg = {
    "#2f3f34",
    "#2d3a32",
    "#2b352f",
    "#29302d",
    "#282c2a",
    "#272928",
  },
}

local styles = {
  normal = { fg = palette.fg, bg = palette.bg },
  normal_nc = { fg = palette.fg, bg = palette.bg },
  dim = { fg = palette.fg_dim },
  muted = { fg = palette.muted },
  subtle = { fg = palette.subtle },
  title = { fg = palette.green, bold = true },
  key = { fg = palette.orange, bold = true },
  separator = { fg = palette.border },
  search = { fg = palette.bg, bg = palette.yellow },
  inc_search = { fg = palette.bg, bg = palette.orange },
  match = { fg = palette.orange, bold = true },
  url = { fg = palette.link, underline = true },

  float = {
    normal = { fg = palette.fg, bg = palette.bg },
    normal_nc = { fg = palette.fg_dim, bg = palette.bg },
    border = { fg = palette.border, bg = palette.bg },
    title = { fg = palette.green, bg = palette.bg, bold = true },
    separator = { fg = palette.border, bg = palette.bg },
    backdrop = { bg = palette.bg_dark },
  },

  popup = {
    normal = { fg = palette.fg, bg = palette.bg_alt },
    border = { fg = palette.green, bg = palette.bg_alt },
    selected = { bg = palette.selection },
  },

  popup_editor = {
    normal = { fg = palette.fg, bg = palette.bg },
    border = { fg = palette.green, bg = palette.bg },
    title = { fg = palette.green, bg = palette.bg, bold = true },
    progress_done = { fg = palette.bg_dark, bg = palette.green, bold = true },
    progress_todo = { fg = palette.subtle, bg = palette.selection },
  },

  input = {
    prompt = { fg = palette.green },
  },

  input_editor = {
    normal = { fg = palette.fg, bg = palette.bg },
    border = { fg = palette.green, bg = palette.bg },
    title = { fg = palette.green, bg = palette.bg, bold = true },
  },

  message = {
    area = { fg = palette.fg_dim },
    separator = { fg = palette.border },
    error = { fg = palette.red },
    warning = { fg = palette.orange },
  },

  statusline = {
    section = { fg = palette.fg_dim, bg = palette.bg_dark },
    inactive = { fg = palette.subtle, bg = palette.bg_dark },
    mode = function(color)
      return { fg = palette.bg_dark, bg = color }
    end,
  },

  tabline = {
    current = { fg = palette.fg, bg = palette.bg_alt, bold = true },
    visible = { fg = palette.fg_dim, bg = palette.bg_dark },
    hidden = { fg = palette.muted, bg = palette.bg_dark },
    fill = { fg = palette.subtle, bg = palette.bg_dark },
    focus_indicator = { fg = palette.green, bg = palette.bg_alt, bold = true },
    trunc = { fg = palette.subtle, bg = palette.bg_dark },
  },

  diagnostic = {
    error = { fg = palette.red },
    warn = { fg = palette.orange },
    info = { fg = palette.blue },
    hint = { fg = palette.green },
  },

  diff = {
    add = { fg = palette.diff_add_fg },
    change = { fg = palette.diff_change_fg },
    delete = { fg = palette.diff_delete_fg },
    add_bg = { bg = palette.diff_add_bg },
    delete_inline = { fg = palette.diff_delete_fg, bg = palette.diff_delete_bg },
  },

  syntax = {
    comment = { fg = palette.comment, italic = true },
    string = { fg = palette.string },
    number = { fg = palette.number },
    float = { fg = palette.number },
    boolean = { fg = palette.boolean },
    constant = { fg = palette.constant },
    conditional = { fg = palette.keyword, italic = true },
    repeat_ = { fg = palette.keyword, italic = true },
    label = { fg = palette.property },
    keyword = { fg = palette.keyword, italic = true },
  },

  kind = {
    text = { fg = palette.fg },
    method = { fg = palette.entity },
    function_ = { fg = palette.entity },
    constructor = { fg = palette.class },
    field = { fg = palette.property },
    variable = { fg = palette.variable },
    class = { fg = palette.class },
    interface = { fg = palette.interface },
    module = { fg = palette.namespace },
    namespace = { fg = palette.namespace },
    property = { fg = palette.property },
    unit = { fg = palette.number },
    value = { fg = palette.constant },
    enum = { fg = palette.class },
    keyword = { fg = palette.keyword, italic = true },
    snippet = { fg = palette.magenta },
    color = { fg = palette.cyan },
    file = { fg = palette.green },
    reference = { fg = palette.link },
    folder = { fg = palette.green },
    enum_member = { fg = palette.constant },
    constant = { fg = palette.constant },
    struct = { fg = palette.class },
    event = { fg = palette.orange },
    operator = { fg = palette.operator },
    type_parameter = { fg = palette.primitive },
    package = { fg = palette.namespace },
    array = { fg = palette.cyan },
    object = { fg = palette.cyan },
    key = { fg = palette.property },
    null = { fg = palette.muted },
    number = { fg = palette.number },
    boolean = { fg = palette.boolean },
  },
}

if vim.g.colors_name then
  vim.cmd.highlight("clear")
end

if vim.fn.exists("syntax_on") == 1 then
  vim.cmd.syntax("reset")
end

vim.g.colors_name = "undefined"

local function heading(level)
  return vim.tbl_extend("force", styles.title, { bg = palette.markdown_heading_bg[level] })
end

local highlights = {
  Normal = styles.normal,
  NormalNC = styles.normal_nc,
  NormalFloat = styles.float.normal,
  FloatBorder = styles.float.border,
  FloatTitle = styles.float.title,
  ColorColumn = { bg = palette.bg_alt },
  CursorLine = { bg = palette.bg_alt },
  CursorColumn = { bg = palette.bg_alt },
  CursorLineNr = { fg = palette.green, bg = palette.selection, bold = true },
  LineNr = { fg = palette.subtle },
  Folded = { fg = palette.muted, bg = palette.bg_alt },
  FoldColumn = { fg = palette.muted, bg = palette.bg },
  SignColumn = { bg = palette.bg },
  VertSplit = { fg = palette.border, bg = palette.bg },
  WinSeparator = { fg = palette.border, bg = palette.bg },
  Visual = { bg = palette.selection },
  VisualNOS = { bg = palette.inactive_selection },
  Search = styles.search,
  IncSearch = styles.inc_search,
  CurSearch = styles.search,
  Substitute = styles.inc_search,
  MatchParen = { fg = palette.green, bg = palette.bg_alt, bold = true },
  Pmenu = { fg = palette.fg, bg = palette.bg_alt },
  PmenuSel = { fg = palette.fg, bg = palette.selection },
  PmenuSbar = { bg = palette.bg_alt },
  PmenuThumb = { bg = palette.subtle },
  Question = styles.input.prompt,
  MoreMsg = { fg = palette.green },
  MsgArea = styles.message.area,
  MsgSeparator = styles.message.separator,
  ModeMsg = { fg = palette.fg_dim },
  NonText = { fg = palette.subtle },
  EndOfBuffer = { fg = palette.bg },
  SpecialKey = { fg = palette.subtle },
  Whitespace = { fg = palette.whitespace },
  StatusLine = { fg = palette.fg_dim, bg = palette.bg_dark },
  StatusLineNC = { fg = palette.subtle, bg = palette.bg_dark },
  TabLine = { fg = palette.muted, bg = palette.bg },
  TabLineFill = { bg = palette.bg_dark },
  TabLineSel = { fg = palette.fg, bg = palette.selection, bold = true },
  WinBar = { fg = palette.green, bg = palette.bg, bold = true },
  WinBarNC = { fg = palette.subtle, bg = palette.bg },

  Comment = styles.syntax.comment,
  Constant = { fg = palette.constant },
  String = styles.syntax.string,
  Character = styles.syntax.string,
  Number = styles.syntax.number,
  Boolean = styles.syntax.boolean,
  Float = styles.syntax.float,
  Identifier = { fg = palette.variable },
  Function = { fg = palette.entity },
  Statement = { fg = palette.keyword, italic = true },
  Conditional = styles.syntax.conditional,
  Repeat = styles.syntax.repeat_,
  Label = styles.syntax.label,
  Operator = { fg = palette.operator },
  Keyword = styles.syntax.keyword,
  Exception = { fg = palette.red },
  PreProc = { fg = palette.keyword, italic = true },
  Include = { fg = palette.entity },
  Define = { fg = palette.keyword, italic = true },
  Macro = { fg = palette.magenta },
  Type = { fg = palette.primitive },
  StorageClass = { fg = palette.storage, italic = true },
  Structure = { fg = palette.primitive },
  Special = { fg = palette.support },
  SpecialChar = { fg = palette.yellow },
  Delimiter = { fg = palette.delimiter },
  Underlined = { fg = palette.link, underline = true },
  Error = { fg = palette.invalid },
  Todo = { fg = palette.yellow, bg = palette.bg_alt, bold = true },

  DiagnosticError = styles.diagnostic.error,
  DiagnosticWarn = styles.diagnostic.warn,
  DiagnosticInfo = styles.diagnostic.info,
  DiagnosticHint = styles.diagnostic.hint,
  DiagnosticFloatingError = styles.diagnostic.error,
  DiagnosticFloatingWarn = styles.diagnostic.warn,
  DiagnosticFloatingInfo = styles.diagnostic.info,
  DiagnosticFloatingHint = styles.diagnostic.hint,
  DiagnosticUnderlineError = { sp = palette.red, undercurl = true },
  DiagnosticUnderlineWarn = { sp = palette.orange, undercurl = true },
  DiagnosticUnderlineInfo = { sp = palette.blue, undercurl = true },
  DiagnosticUnderlineHint = { sp = palette.green, undercurl = true },
  LspReferenceText = { bg = palette.selection },
  LspReferenceRead = { bg = palette.selection },
  LspReferenceWrite = { bg = palette.selection },

  DiffAdd = { bg = palette.diff_add_bg },
  DiffChange = { bg = palette.diff_change_bg },
  DiffDelete = { bg = palette.diff_delete_bg },
  DiffText = { bg = palette.diff_text_bg },

  Directory = styles.kind.folder,
  Title = styles.title,
  ErrorMsg = styles.message.error,
  WarningMsg = styles.message.warning,

  helpHyperTextJump = styles.url,
  helpHyperTextEntry = styles.url,
  helpURL = styles.url,

  markdownLinkText = styles.url,
  markdownUrl = styles.url,

  ["@comment"] = styles.syntax.comment,
  ["@punctuation"] = { fg = palette.delimiter },
  ["@operator"] = { fg = palette.operator },

  ["@string"] = styles.syntax.string,
  ["@string.documentation"] = { fg = palette.comment },
  ["@string.escape"] = { fg = palette.yellow },
  ["@string.regexp"] = { fg = palette.regexp },
  ["@string.special"] = { fg = palette.string },
  ["@string.special.url"] = styles.url,

  ["@number"] = styles.syntax.number,
  ["@number.float"] = styles.syntax.float,
  ["@boolean"] = styles.syntax.boolean,
  ["@constant"] = styles.syntax.constant,
  ["@constant.builtin"] = { fg = palette.storage },
  ["@constant.macro"] = { fg = palette.constant },

  ["@variable"] = { fg = palette.variable },
  ["@variable.builtin"] = { fg = palette.constant },
  ["@variable.parameter"] = { fg = palette.variable },
  ["@variable.member"] = { fg = palette.property },
  ["@property"] = { fg = palette.property },
  ["@field"] = { fg = palette.property },

  ["@function"] = { fg = palette.entity },
  ["@function.builtin"] = { fg = palette.support },
  ["@function.call"] = { fg = palette.entity },
  ["@function.macro"] = { fg = palette.entity },
  ["@method"] = { fg = palette.entity },
  ["@method.call"] = { fg = palette.entity },
  ["@constructor"] = { fg = palette.class },

  ["@keyword"] = styles.syntax.keyword,
  ["@keyword.function"] = styles.syntax.keyword,
  ["@keyword.operator"] = { fg = palette.operator },
  ["@keyword.return"] = styles.syntax.keyword,
  ["@conditional"] = styles.syntax.conditional,
  ["@repeat"] = styles.syntax.repeat_,
  ["@label"] = styles.syntax.label,

  ["@type"] = { fg = palette.primitive },
  ["@type.builtin"] = { fg = palette.storage },
  ["@type.definition"] = { fg = palette.primitive },
  ["@type.qualifier"] = { fg = palette.storage, italic = true },

  ["@tag"] = { fg = palette.tag },
  ["@tag.attribute"] = { fg = palette.attribute },
  ["@tag.delimiter"] = { fg = palette.delimiter },

  ["@markup.heading"] = styles.title,
  ["@markup.heading.1"] = heading(1),
  ["@markup.heading.2"] = heading(2),
  ["@markup.heading.3"] = heading(3),
  ["@markup.heading.4"] = heading(4),
  ["@markup.heading.5"] = heading(5),
  ["@markup.heading.6"] = heading(6),
  ["@markup.heading.1.markdown"] = heading(1),
  ["@markup.heading.2.markdown"] = heading(2),
  ["@markup.heading.3.markdown"] = heading(3),
  ["@markup.heading.4.markdown"] = heading(4),
  ["@markup.heading.5.markdown"] = heading(5),
  ["@markup.heading.6.markdown"] = heading(6),
  ["@markup.strong"] = { fg = palette.fg, bold = true },
  ["@markup.italic"] = { fg = palette.fg, italic = true },
  ["@markup.quote"] = { fg = palette.interface },
  ["@markup.raw"] = { fg = palette.green },
  ["@markup.link"] = styles.url,
  ["@markup.link.url"] = styles.url,
  ["@text.reference"] = styles.url,
  ["@markup.list"] = { fg = palette.orange },

  ["@diff.plus"] = { fg = palette.diff_add_fg, bg = palette.diff_add_bg },
  ["@diff.minus"] = { fg = palette.diff_delete_fg, bg = palette.diff_delete_bg },
  ["@diff.delta"] = { fg = palette.diff_change_fg },

  ["@module"] = { fg = palette.namespace },
  ["@namespace"] = { fg = palette.namespace },

  ["@lsp.type.namespace"] = { fg = palette.namespace },
  ["@lsp.type.module"] = { fg = palette.namespace },
  ["@lsp.type.property"] = { fg = palette.property },
  ["@lsp.type.interface"] = { fg = palette.interface },
  ["@lsp.type.type"] = { fg = palette.interface },
  ["@lsp.type.class"] = { fg = palette.class },
  ["@lsp.type.component.vue"] = { fg = palette.class },
  ["@lsp.type.enum"] = { fg = palette.class },
  ["@lsp.type.struct"] = { fg = palette.class },
  ["@lsp.type.function"] = { fg = palette.entity },
  ["@lsp.type.method"] = { fg = palette.entity },
  ["@lsp.type.macro"] = { fg = palette.entity },
  ["@lsp.type.variable"] = { fg = palette.variable },
  ["@lsp.type.parameter"] = { fg = palette.variable },
  ["@lsp.type.decorator"] = { fg = palette.attribute },
  ["@lsp.type.const"] = { fg = palette.constant },
  ["@lsp.type.enumMember"] = { fg = palette.constant },

  ["@keyword.gitcommit"] = { fg = palette.green, bold = true },
  ["@variable.parameter.gitcommit"] = { fg = palette.blue, bold = true },
  ["@markup.heading.gitcommit"] = { fg = palette.fg_dim, bold = true },
  ["@function.gitcommit"] = { fg = palette.magenta, bold = true },
  ["@punctuation.delimiter.gitcommit"] = { fg = palette.subtle },
  ["@punctuation.special.gitcommit"] = { fg = palette.red, bold = true },
  ["@string.special.path.gitcommit"] = { fg = palette.cyan },
  ["@label.gitcommit"] = { fg = palette.orange, bold = true },
  ["@comment.error.gitcommit"] = { fg = palette.red, bold = true },

  BlinkCmpLabel = { fg = palette.fg },
  BlinkCmpLabelMatch = styles.match,
  BlinkCmpLabelDeprecated = { fg = palette.subtle, strikethrough = true },
  BlinkCmpLabelDetail = { fg = palette.muted },
  BlinkCmpLabelDescription = { fg = palette.comment },
  BlinkCmpSource = { fg = palette.muted },
  BlinkCmpKind = { fg = palette.green },
  BlinkCmpKindText = styles.kind.text,
  BlinkCmpKindMethod = styles.kind.method,
  BlinkCmpKindFunction = styles.kind.function_,
  BlinkCmpKindConstructor = styles.kind.constructor,
  BlinkCmpKindField = styles.kind.field,
  BlinkCmpKindVariable = styles.kind.variable,
  BlinkCmpKindClass = styles.kind.class,
  BlinkCmpKindInterface = styles.kind.interface,
  BlinkCmpKindModule = styles.kind.module,
  BlinkCmpKindProperty = styles.kind.property,
  BlinkCmpKindUnit = styles.kind.unit,
  BlinkCmpKindValue = styles.kind.value,
  BlinkCmpKindEnum = styles.kind.enum,
  BlinkCmpKindKeyword = styles.kind.keyword,
  BlinkCmpKindSnippet = styles.kind.snippet,
  BlinkCmpKindColor = styles.kind.color,
  BlinkCmpKindFile = styles.kind.file,
  BlinkCmpKindReference = styles.kind.reference,
  BlinkCmpKindFolder = styles.kind.folder,
  BlinkCmpKindEnumMember = styles.kind.enum_member,
  BlinkCmpKindConstant = styles.kind.constant,
  BlinkCmpKindStruct = styles.kind.struct,
  BlinkCmpKindEvent = styles.kind.event,
  BlinkCmpKindOperator = styles.kind.operator,
  BlinkCmpKindTypeParameter = styles.kind.type_parameter,
  BlinkCmpScrollBarThumb = { bg = palette.subtle },
  BlinkCmpScrollBarGutter = { bg = palette.bg_alt },
  BlinkCmpGhostText = { fg = palette.subtle },
  BlinkCmpMenu = styles.popup.normal,
  BlinkCmpMenuBorder = styles.popup.border,
  BlinkCmpMenuSelection = styles.popup.selected,
  BlinkCmpDoc = styles.float.normal,
  BlinkCmpDocBorder = styles.float.border,
  BlinkCmpDocSeparator = styles.float.border,
  BlinkCmpDocCursorLine = { bg = palette.bg_alt },
  BlinkCmpSignatureHelp = styles.float.normal,
  BlinkCmpSignatureHelpBorder = styles.float.border,
  BlinkCmpSignatureHelpActiveParameter = { bg = palette.selection, bold = true },

  MiniStatuslineModeNormal = styles.statusline.mode(palette.green),
  MiniStatuslineModeInsert = styles.statusline.mode(palette.blue),
  MiniStatuslineModeVisual = styles.statusline.mode(palette.magenta),
  MiniStatuslineModeReplace = styles.statusline.mode(palette.red),
  MiniStatuslineModeCommand = styles.statusline.mode(palette.yellow),
  MiniStatuslineModeOther = styles.statusline.mode(palette.cyan),
  MiniStatuslineDevinfo = styles.statusline.section,
  MiniStatuslineWorkspace = { fg = palette.green, bg = palette.bg_alt, bold = true },
  MiniStatuslinePath = styles.statusline.section,
  MiniStatuslineDiagnostics = styles.statusline.section,
  MiniStatuslineInputState = styles.statusline.section,
  MiniStatuslineMetadata = styles.statusline.section,
  MiniStatuslineDirectory = { fg = palette.comment, bg = palette.bg_dark },
  MiniStatuslineFilename = { fg = palette.fg, bg = palette.bg_dark },
  MiniStatuslineInactive = styles.statusline.inactive,
  MiniStatuslineDiffAdd = { fg = palette.diff_add_fg, bg = palette.bg_dark },
  MiniStatuslineDiffChange = { fg = palette.diff_change_fg, bg = palette.bg_dark },
  MiniStatuslineDiffDelete = { fg = palette.diff_delete_fg, bg = palette.bg_dark },
  MiniStatuslineDiagnosticError = { fg = palette.red, bg = palette.bg_dark },
  MiniStatuslineDiagnosticWarn = { fg = palette.orange, bg = palette.bg_dark },
  MiniStatuslineDiagnosticInfo = { fg = palette.blue, bg = palette.bg_dark },
  MiniStatuslineDiagnosticHint = { fg = palette.green, bg = palette.bg_dark },
  MiniTablineCurrent = vim.tbl_extend("force", styles.tabline.current, { bg = palette.selection }),
  MiniTablineVisible = styles.tabline.visible,
  MiniTablineHidden = styles.tabline.hidden,
  MiniTablineModifiedCurrent = vim.tbl_extend(
    "force",
    styles.tabline.current,
    { fg = palette.orange, bg = palette.selection }
  ),
  MiniTablineModifiedVisible = vim.tbl_extend("force", styles.tabline.visible, { fg = palette.orange }),
  MiniTablineModifiedHidden = vim.tbl_extend("force", styles.tabline.hidden, { fg = palette.orange }),
  MiniTablineFill = styles.tabline.fill,
  MiniTablineTabpagesection = styles.tabline.focus_indicator,
  MiniTablineTrunc = styles.tabline.trunc,
  MiniHipatternsFixme = { fg = palette.bg, bg = palette.red, bold = true },
  MiniHipatternsHack = { fg = palette.bg, bg = palette.orange, bold = true },
  MiniHipatternsNote = { fg = palette.bg, bg = palette.green, bold = true },
  MiniHipatternsPerf = { fg = palette.bg, bg = palette.magenta, bold = true },
  MiniHipatternsTest = { fg = palette.bg, bg = palette.magenta, bold = true },
  MiniHipatternsTodo = { fg = palette.bg, bg = palette.blue, bold = true },
  MiniHipatternsWarn = { fg = palette.bg, bg = palette.orange, bold = true },
  MiniCursorword = { bg = palette.selection, underline = true },
  MiniCursorwordCurrent = { bg = palette.selection, underline = true },
  MiniClueDescGroup = { fg = palette.yellow, bold = true },
  MiniDiffSignAdd = { fg = palette.diff_add_fg, bold = true },
  MiniDiffSignChange = { fg = palette.diff_change_fg, bold = true },
  MiniDiffSignDelete = { fg = palette.diff_delete_fg, bold = true },
  MiniDiffOverAdd = styles.diff.add_bg,
  MiniDiffOverChange = { fg = palette.diff_change_fg, bg = palette.bg_alt },
  MiniDiffOverChangeBuf = { bg = palette.bg_alt },
  MiniDiffOverContext = { fg = palette.subtle, bg = palette.bg_alt },
  MiniDiffOverContextBuf = {},
  MiniDiffOverDelete = styles.diff.delete_inline,
  MiniMapNormal = styles.float.normal,
  MiniMapSymbolCount = { fg = palette.comment },
  MiniMapSymbolLine = { fg = palette.green, bold = true },
  MiniMapSymbolView = { fg = palette.border },
  MiniMapDiagnosticHint = styles.diagnostic.hint,
  MiniMapDiagnosticInfo = styles.diagnostic.info,
  MiniMapDiagnosticWarn = styles.diagnostic.warn,
  MiniMapDiagnosticError = styles.diagnostic.error,
  MiniMapDiffAdd = styles.diff.add,
  MiniMapDiffChange = styles.diff.change,
  MiniMapDiffDelete = styles.diff.delete,
  MiniMapSearch = { fg = palette.orange, bold = true },
  MiniIndentscopeSymbol = { fg = palette.yellow, bold = true },
  MiniIndentscopeSymbolOff = { fg = palette.border },
  MiniJump = { fg = palette.bg, bg = palette.yellow, bold = true },
  MiniJump2dSpot = { fg = palette.bg, bg = palette.yellow, bold = true, nocombine = true },
  MiniJump2dSpotUnique = { fg = palette.bg, bg = palette.yellow, bold = true, nocombine = true },
  MiniJump2dSpotAhead = { fg = palette.bg, bg = palette.orange, nocombine = true },
  MiniIconsAzure = { fg = palette.blue },
  MiniIconsBlue = { fg = palette.blue },
  MiniIconsCyan = { fg = palette.cyan },
  MiniIconsGreen = { fg = palette.green },
  MiniIconsGrey = { fg = palette.muted },
  MiniIconsOrange = { fg = palette.orange },
  MiniIconsPurple = { fg = palette.magenta },
  MiniIconsRed = { fg = palette.red },
  MiniIconsYellow = { fg = palette.yellow },
  MiniFilesHidden = { fg = palette.comment },

  NeogitDiffHeader = { fg = palette.diff_header, bg = palette.bg, bold = true },
  NeogitDiffHeaderHighlight = { fg = palette.diff_header, bg = palette.bg, bold = true },
  NeogitDiffHeaderCursor = { fg = palette.diff_header, bg = palette.bg, bold = true },
  NeogitDiffContext = { bg = palette.bg },
  NeogitDiffContextHighlight = { bg = palette.bg },
  NeogitDiffContextCursor = { bg = palette.bg },
  NeogitDiffAdd = { fg = palette.diff_add_fg, bg = palette.diff_add_bg },
  NeogitDiffAddHighlight = { fg = palette.diff_add_fg, bg = palette.diff_add_bg },
  NeogitDiffAddCursor = { fg = palette.diff_add_fg, bg = palette.diff_add_bg },
  NeogitDiffDelete = { fg = palette.diff_delete_fg, bg = palette.diff_delete_bg },
  NeogitDiffDeleteHighlight = { fg = palette.diff_delete_fg, bg = palette.diff_delete_bg },
  NeogitDiffDeleteCursor = { fg = palette.diff_delete_fg, bg = palette.diff_delete_bg },
  NeogitHunkHeader = { fg = palette.diff_header, bg = palette.bg, bold = true },
  NeogitHunkHeaderHighlight = { fg = palette.diff_header, bg = palette.bg, bold = true },
  NeogitHunkHeaderCursor = { fg = palette.diff_header, bg = palette.bg, bold = true },

  NoiceletFormatProgressDone = styles.popup_editor.progress_done,
  NoiceletFormatProgressTodo = styles.popup_editor.progress_todo,
  NoiceletLspMessageError = styles.diagnostic.error,
  NoiceletLspMessageInfo = styles.diagnostic.info,
  NoiceletLspMessageLog = { fg = palette.muted },
  NoiceletLspMessageWarn = styles.diagnostic.warn,
  NoiceletLspProgressClient = { fg = palette.muted },
  NoiceletLspProgressSpinner = { fg = palette.cyan },
  NoiceletLspProgressTitle = { fg = palette.fg },
  NoiceletMini = { fg = palette.fg_dim },

  SnacksNormal = styles.float.normal,
  SnacksNormalNC = styles.float.normal_nc,
  SnacksWinBar = vim.tbl_extend("force", styles.popup_editor.title, { fg = palette.fg }),
  SnacksWinBarNC = { fg = palette.muted, bg = styles.popup_editor.normal.bg },
  SnacksTitle = styles.popup_editor.title,
  SnacksFooter = styles.dim,
  SnacksFooterKey = styles.key,
  SnacksFooterDesc = styles.muted,
  SnacksBackdrop = styles.float.backdrop,
  SnacksWinSeparator = styles.float.separator,
  SnacksWinKey = styles.key,
  SnacksWinKeySep = styles.separator,
  SnacksWinKeyDesc = styles.dim,

  SnacksPicker = styles.popup_editor.normal,
  SnacksPickerBox = styles.popup_editor.normal,
  SnacksPickerBoxBorder = styles.popup_editor.border,
  SnacksPickerBoxTitle = styles.popup_editor.title,
  SnacksPickerBorder = styles.popup_editor.border,
  SnacksPickerTitle = styles.popup_editor.title,
  SnacksPickerCursorLine = styles.popup.selected,
  SnacksPickerInput = styles.popup_editor.normal,
  SnacksPickerInputBorder = styles.popup_editor.border,
  SnacksPickerInputTitle = styles.popup_editor.title,
  SnacksPickerList = styles.popup_editor.normal,
  SnacksPickerListBorder = styles.popup_editor.border,
  SnacksPickerListCursorLine = styles.popup.selected,
  SnacksPickerListTitle = styles.popup_editor.title,
  SnacksPickerPreview = styles.popup_editor.normal,
  SnacksPickerPreviewBorder = styles.popup_editor.border,
  SnacksPickerPreviewTitle = styles.popup_editor.title,
  SnacksPickerMatch = styles.search,
  SnacksPickerSearch = styles.search,
  SnacksPickerPrompt = styles.input.prompt,
  SnacksPickerInputSearch = { fg = palette.yellow },
  SnacksPickerSpecial = { fg = palette.support },
  SnacksPickerLabel = { fg = palette.property },
  SnacksPickerTotals = styles.muted,
  SnacksPickerFile = { fg = palette.fg },
  SnacksPickerLink = styles.url,
  SnacksPickerLinkBroken = { fg = palette.red, underline = true },
  SnacksPickerDirectory = { fg = palette.green },
  SnacksPickerPathIgnored = styles.subtle,
  SnacksPickerPathHidden = styles.muted,
  SnacksPickerDir = { fg = palette.green },
  SnacksPickerToggle = { fg = palette.orange },
  SnacksPickerDimmed = styles.subtle,
  SnacksPickerRow = { fg = palette.number },
  SnacksPickerCol = { fg = palette.number },
  SnacksPickerComment = styles.syntax.comment,
  SnacksPickerDesc = styles.dim,
  SnacksPickerDelim = { fg = palette.delimiter },
  SnacksPickerSpinner = { fg = palette.cyan },
  SnacksPickerSelected = { fg = palette.green, bold = true },
  SnacksPickerCmd = { fg = palette.entity },
  SnacksPickerCmdBuiltin = { fg = palette.support },
  SnacksPickerUnselected = styles.subtle,
  SnacksPickerIdx = styles.muted,
  SnacksPickerBold = { fg = palette.fg, bold = true },
  SnacksPickerTree = styles.subtle,
  SnacksPickerItalic = { fg = palette.fg_dim, italic = true },
  SnacksPickerCode = styles.syntax.string,
  SnacksPickerAuPattern = styles.syntax.string,
  SnacksPickerAuEvent = styles.syntax.keyword,
  SnacksPickerAuGroup = { fg = palette.namespace },
  SnacksPickerDiagnosticCode = styles.muted,
  SnacksPickerDiagnosticSource = { fg = palette.comment },
  SnacksPickerRegister = { fg = palette.orange },
  SnacksPickerKeymapMode = { fg = palette.magenta },
  SnacksPickerKeymapLhs = styles.key,
  SnacksPickerKeymapNowait = { fg = palette.orange },
  SnacksPickerKeymapRhs = styles.dim,
  SnacksPickerBufNr = { fg = palette.number },
  SnacksPickerBufFlags = { fg = palette.orange },
  SnacksPickerBufType = { fg = palette.interface },
  SnacksPickerFileType = { fg = palette.primitive },
  SnacksPickerTime = styles.muted,
  SnacksPickerUndoAdded = styles.diff.add,
  SnacksPickerUndoRemoved = styles.diff.delete,
  SnacksPickerUndoCurrent = { fg = palette.yellow, bold = true },
  SnacksPickerUndoSaved = { fg = palette.green },
  SnacksPickerGitCommit = { fg = palette.yellow },
  SnacksPickerGitBreaking = { fg = palette.red, bold = true },
  SnacksPickerGitDetached = { fg = palette.orange },
  SnacksPickerGitBranch = { fg = palette.green },
  SnacksPickerGitBranchCurrent = { fg = palette.green, bold = true },
  SnacksPickerGitDate = styles.muted,
  SnacksPickerGitIssue = { fg = palette.link },
  SnacksPickerGitAuthor = { fg = palette.attribute },
  SnacksPickerGitType = { fg = palette.magenta },
  SnacksPickerGitScope = { fg = palette.namespace },
  SnacksPickerGitStatus = styles.muted,
  SnacksPickerGitStatusAdded = styles.diff.add,
  SnacksPickerGitStatusModified = styles.diff.change,
  SnacksPickerGitStatusDeleted = styles.diff.delete,
  SnacksPickerGitStatusRenamed = { fg = palette.cyan },
  SnacksPickerGitStatusCopied = { fg = palette.cyan },
  SnacksPickerGitStatusUntracked = { fg = palette.orange },
  SnacksPickerGitStatusIgnored = styles.subtle,
  SnacksPickerGitStatusUnmerged = { fg = palette.red },
  SnacksPickerGitStatusStaged = { fg = palette.green, bold = true },
  SnacksPickerManSection = { fg = palette.magenta },
  SnacksPickerPickWin = { fg = palette.bg, bg = palette.yellow, bold = true },
  SnacksPickerPickWinCurrent = { fg = palette.bg, bg = palette.green, bold = true },
  SnacksPickerLspDisabled = styles.subtle,
  SnacksPickerLspEnabled = { fg = palette.green },
  SnacksPickerLspAttached = { fg = palette.green },
  SnacksPickerLspAttachedBuf = { fg = palette.cyan },
  SnacksPickerLspUnavailable = { fg = palette.red },
  SnacksPickerManPage = { fg = palette.fg },
  SnacksPickerIcon = { fg = palette.green },
  SnacksPickerIconSource = styles.muted,
  SnacksPickerIconName = { fg = palette.fg },
  SnacksPickerIconCategory = { fg = palette.magenta },
  SnacksPickerIconArray = styles.kind.array,
  SnacksPickerIconBoolean = styles.kind.boolean,
  SnacksPickerIconClass = styles.kind.class,
  SnacksPickerIconConstant = styles.kind.constant,
  SnacksPickerIconConstructor = styles.kind.constructor,
  SnacksPickerIconEnum = styles.kind.enum,
  SnacksPickerIconEnumMember = styles.kind.enum_member,
  SnacksPickerIconEvent = styles.kind.event,
  SnacksPickerIconField = styles.kind.field,
  SnacksPickerIconFile = styles.kind.file,
  SnacksPickerIconFunction = styles.kind.function_,
  SnacksPickerIconInterface = styles.kind.interface,
  SnacksPickerIconKey = styles.kind.key,
  SnacksPickerIconMethod = styles.kind.method,
  SnacksPickerIconModule = styles.kind.module,
  SnacksPickerIconNamespace = styles.kind.namespace,
  SnacksPickerIconNull = styles.kind.null,
  SnacksPickerIconNumber = styles.kind.number,
  SnacksPickerIconObject = styles.kind.object,
  SnacksPickerIconOperator = styles.kind.operator,
  SnacksPickerIconPackage = styles.kind.package,
  SnacksPickerIconProperty = styles.kind.property,
  SnacksPickerIconString = styles.syntax.string,
  SnacksPickerIconStruct = styles.kind.struct,
  SnacksPickerIconTypeParameter = styles.kind.type_parameter,
  SnacksPickerIconVariable = styles.kind.variable,
  SnacksPickerRule = { fg = palette.border },
  SnacksDiffHeader = { fg = palette.fg_dim, bg = palette.bg_alt },
  SnacksDiffLabel = { fg = palette.property, bg = palette.bg_alt, bold = true },

  SnacksNotifierHistory = styles.float.normal,
  SnacksNotifierHistoryTitle = styles.title,
  SnacksNotifierHistoryDateTime = styles.muted,
  SnacksNotifierMinimal = styles.float.normal,
  SnacksInputIcon = { fg = palette.green },
  SnacksInputNormal = styles.input_editor.normal,
  SnacksInputBorder = styles.input_editor.border,
  SnacksInputTitle = styles.input_editor.title,
  SnacksInputPrompt = styles.input.prompt,
  SnacksStatusColumnMark = { fg = palette.yellow, bold = true },

  TreesitterContext = { bg = palette.bg_alt },
  TreesitterContextLineNumber = { fg = palette.subtle, bg = palette.bg_alt },
  TreesitterContextLineNumberBottom = { fg = palette.fg_dim, bg = palette.bg_alt, underline = true },
  TreesitterContextSeparator = { fg = styles.float.separator.fg, bg = palette.bg_alt },

  MiniTablineIconAzureCurrent = { fg = palette.blue, bg = palette.selection },
  MiniTablineIconAzureInactive = { fg = palette.blue, bg = palette.bg_dark },
  MiniTablineIconBlueCurrent = { fg = palette.blue, bg = palette.selection },
  MiniTablineIconBlueInactive = { fg = palette.blue, bg = palette.bg_dark },
  MiniTablineIconCyanCurrent = { fg = palette.cyan, bg = palette.selection },
  MiniTablineIconCyanInactive = { fg = palette.cyan, bg = palette.bg_dark },
  MiniTablineIconGreenCurrent = { fg = palette.green, bg = palette.selection },
  MiniTablineIconGreenInactive = { fg = palette.green, bg = palette.bg_dark },
  MiniTablineIconGreyCurrent = { fg = palette.muted, bg = palette.selection },
  MiniTablineIconGreyInactive = { fg = palette.muted, bg = palette.bg_dark },
  MiniTablineIconOrangeCurrent = { fg = palette.orange, bg = palette.selection },
  MiniTablineIconOrangeInactive = { fg = palette.orange, bg = palette.bg_dark },
  MiniTablineIconPurpleCurrent = { fg = palette.magenta, bg = palette.selection },
  MiniTablineIconPurpleInactive = { fg = palette.magenta, bg = palette.bg_dark },
  MiniTablineIconRedCurrent = { fg = palette.red, bg = palette.selection },
  MiniTablineIconRedInactive = { fg = palette.red, bg = palette.bg_dark },
  MiniTablineIconYellowCurrent = { fg = palette.yellow, bg = palette.selection },
  MiniTablineIconYellowInactive = { fg = palette.yellow, bg = palette.bg_dark },

  SnacksNotifierInfo = { fg = palette.blue, bg = palette.bg },
  SnacksNotifierIconInfo = { fg = palette.blue, bg = palette.bg },
  SnacksNotifierBorderInfo = { fg = palette.blue, bg = palette.bg },
  SnacksNotifierTitleInfo = { fg = palette.blue, bg = palette.bg, bold = true },
  SnacksNotifierFooterInfo = { fg = palette.blue, bg = palette.bg },
  SnacksNotifierWarn = { fg = palette.orange, bg = palette.bg },
  SnacksNotifierIconWarn = { fg = palette.orange, bg = palette.bg },
  SnacksNotifierBorderWarn = { fg = palette.orange, bg = palette.bg },
  SnacksNotifierTitleWarn = { fg = palette.orange, bg = palette.bg, bold = true },
  SnacksNotifierFooterWarn = { fg = palette.orange, bg = palette.bg },
  SnacksNotifierError = { fg = palette.red, bg = palette.bg },
  SnacksNotifierIconError = { fg = palette.red, bg = palette.bg },
  SnacksNotifierBorderError = { fg = palette.red, bg = palette.bg },
  SnacksNotifierTitleError = { fg = palette.red, bg = palette.bg, bold = true },
  SnacksNotifierFooterError = { fg = palette.red, bg = palette.bg },
  SnacksNotifierDebug = { fg = palette.magenta, bg = palette.bg },
  SnacksNotifierIconDebug = { fg = palette.magenta, bg = palette.bg },
  SnacksNotifierBorderDebug = { fg = palette.magenta, bg = palette.bg },
  SnacksNotifierTitleDebug = { fg = palette.magenta, bg = palette.bg, bold = true },
  SnacksNotifierFooterDebug = { fg = palette.magenta, bg = palette.bg },
  SnacksNotifierTrace = { fg = palette.muted, bg = palette.bg },
  SnacksNotifierIconTrace = { fg = palette.muted, bg = palette.bg },
  SnacksNotifierBorderTrace = { fg = palette.muted, bg = palette.bg },
  SnacksNotifierTitleTrace = { fg = palette.muted, bg = palette.bg, bold = true },
  SnacksNotifierFooterTrace = { fg = palette.muted, bg = palette.bg },
}

for group, spec in pairs(highlights) do
  vim.api.nvim_set_hl(0, group, spec)
end
