local M = {}
local styles = require("colors.undefined.styles")

function M.get(p)
  local s = styles.get(p)

  local function markdown_heading(level)
    return styles.extend(s.title, { bg = p.markdown_heading_bg[level] })
  end

  return {
    Normal = s.normal,
    NormalNC = s.normal_nc,
    NormalFloat = s.float.normal,
    FloatBorder = s.float.border,
    FloatTitle = s.float.title,
    ColorColumn = { bg = p.bg_alt },
    CursorLine = { bg = p.bg_alt },
    CursorColumn = { bg = p.bg_alt },
    CursorLineNr = { fg = p.fg_dim, bold = true },
    LineNr = { fg = p.subtle },
    Folded = { fg = p.muted, bg = p.bg_alt },
    FoldColumn = { fg = p.muted, bg = p.bg },
    SignColumn = { bg = p.bg },
    VertSplit = { fg = p.border, bg = p.bg },
    WinSeparator = { fg = p.border, bg = p.bg },
    Visual = { bg = p.selection },
    VisualNOS = { bg = p.inactive_selection },
    Search = { fg = p.bg, bg = p.yellow },
    IncSearch = { fg = p.bg, bg = p.orange },
    CurSearch = { fg = p.bg, bg = p.yellow },
    Substitute = { fg = p.bg, bg = p.orange },
    MatchParen = { fg = p.green, bg = p.bg_alt, bold = true },
    Pmenu = { fg = p.fg, bg = p.bg_alt },
    PmenuSel = { fg = p.fg, bg = p.selection },
    PmenuSbar = { bg = p.bg_alt },
    PmenuThumb = { bg = p.subtle },
    Question = s.input.prompt,
    MoreMsg = { fg = p.green },
    MsgArea = s.message.area,
    MsgSeparator = s.message.separator,
    ModeMsg = { fg = p.fg_dim },
    NonText = { fg = p.subtle },
    EndOfBuffer = { fg = p.bg },
    SpecialKey = { fg = p.subtle },
    Whitespace = { fg = p.whitespace },
    StatusLine = { fg = p.fg_dim, bg = p.bg_dark },
    StatusLineNC = { fg = p.subtle, bg = p.bg_dark },
    TabLine = { fg = p.muted, bg = p.bg },
    TabLineFill = { bg = p.bg },
    TabLineSel = { fg = p.fg, bg = p.bg_alt, bold = true },

    Comment = s.syntax.comment,
    Constant = { fg = p.constant },
    String = s.syntax.string,
    Character = s.syntax.string,
    Number = s.syntax.number,
    Boolean = s.syntax.boolean,
    Float = s.syntax.float,
    Identifier = { fg = p.variable },
    Function = { fg = p.entity },
    Statement = { fg = p.keyword, italic = true },
    Conditional = s.syntax.conditional,
    Repeat = s.syntax.repeat_,
    Label = s.syntax.label,
    Operator = { fg = p.operator },
    Keyword = s.syntax.keyword,
    Exception = { fg = p.red },
    PreProc = { fg = p.keyword, italic = true },
    Include = { fg = p.entity },
    Define = { fg = p.keyword, italic = true },
    Macro = { fg = p.magenta },
    Type = { fg = p.primitive },
    StorageClass = { fg = p.storage, italic = true },
    Structure = { fg = p.primitive },
    Special = { fg = p.support },
    SpecialChar = { fg = p.yellow },
    Delimiter = { fg = p.delimiter },
    Underlined = { fg = p.link, underline = true },
    Error = { fg = p.invalid },
    Todo = { fg = p.yellow, bg = p.bg_alt, bold = true },

    DiagnosticError = s.diagnostic.error,
    DiagnosticWarn = s.diagnostic.warn,
    DiagnosticInfo = s.diagnostic.info,
    DiagnosticHint = s.diagnostic.hint,
    DiagnosticFloatingError = s.diagnostic.error,
    DiagnosticFloatingWarn = s.diagnostic.warn,
    DiagnosticFloatingInfo = s.diagnostic.info,
    DiagnosticFloatingHint = s.diagnostic.hint,
    DiagnosticUnderlineError = { sp = p.red, undercurl = true },
    DiagnosticUnderlineWarn = { sp = p.orange, undercurl = true },
    DiagnosticUnderlineInfo = { sp = p.blue, undercurl = true },
    DiagnosticUnderlineHint = { sp = p.green, undercurl = true },

    DiffAdd = { bg = p.diff_add_bg },
    DiffChange = {},
    DiffDelete = { bg = p.diff_delete_bg },
    DiffText = { bg = p.bg_alt },

    Directory = s.kind.folder,
    Title = s.title,
    ErrorMsg = s.message.error,
    WarningMsg = s.message.warning,

    helpHyperTextJump = s.url,
    helpHyperTextEntry = s.url,
    helpURL = s.url,

    markdownLinkText = s.url,
    markdownUrl = s.url,

    ["@comment"] = s.syntax.comment,
    ["@punctuation"] = { fg = p.delimiter },
    ["@operator"] = { fg = p.operator },

    ["@string"] = s.syntax.string,
    ["@string.documentation"] = { fg = p.comment },
    ["@string.escape"] = { fg = p.yellow },
    ["@string.regexp"] = { fg = p.regexp },
    ["@string.special"] = { fg = p.string },
    ["@string.special.url"] = s.url,

    ["@number"] = s.syntax.number,
    ["@number.float"] = s.syntax.float,
    ["@boolean"] = s.syntax.boolean,
    ["@constant"] = s.syntax.constant,
    ["@constant.builtin"] = { fg = p.storage },
    ["@constant.macro"] = { fg = p.constant },

    ["@variable"] = { fg = p.variable },
    ["@variable.builtin"] = { fg = p.constant },
    ["@variable.parameter"] = { fg = p.variable },
    ["@variable.member"] = { fg = p.property },
    ["@property"] = { fg = p.property },
    ["@field"] = { fg = p.property },

    ["@function"] = { fg = p.entity },
    ["@function.builtin"] = { fg = p.support },
    ["@function.call"] = { fg = p.entity },
    ["@function.macro"] = { fg = p.entity },
    ["@method"] = { fg = p.entity },
    ["@method.call"] = { fg = p.entity },
    ["@constructor"] = { fg = p.class },

    ["@keyword"] = s.syntax.keyword,
    ["@keyword.function"] = s.syntax.keyword,
    ["@keyword.operator"] = { fg = p.operator },
    ["@keyword.return"] = s.syntax.keyword,
    ["@conditional"] = s.syntax.conditional,
    ["@repeat"] = s.syntax.repeat_,
    ["@label"] = s.syntax.label,

    ["@type"] = { fg = p.primitive },
    ["@type.builtin"] = { fg = p.storage },
    ["@type.definition"] = { fg = p.primitive },
    ["@type.qualifier"] = { fg = p.storage, italic = true },

    ["@tag"] = { fg = p.tag },
    ["@tag.attribute"] = { fg = p.attribute },
    ["@tag.delimiter"] = { fg = p.delimiter },

    ["@markup.heading"] = s.title,
    ["@markup.heading.1"] = markdown_heading(1),
    ["@markup.heading.2"] = markdown_heading(2),
    ["@markup.heading.3"] = markdown_heading(3),
    ["@markup.heading.4"] = markdown_heading(4),
    ["@markup.heading.5"] = markdown_heading(5),
    ["@markup.heading.6"] = markdown_heading(6),
    ["@markup.heading.1.markdown"] = markdown_heading(1),
    ["@markup.heading.2.markdown"] = markdown_heading(2),
    ["@markup.heading.3.markdown"] = markdown_heading(3),
    ["@markup.heading.4.markdown"] = markdown_heading(4),
    ["@markup.heading.5.markdown"] = markdown_heading(5),
    ["@markup.heading.6.markdown"] = markdown_heading(6),
    ["@markup.strong"] = { fg = p.fg, bold = true },
    ["@markup.italic"] = { fg = p.fg, italic = true },
    ["@markup.quote"] = { fg = p.interface },
    ["@markup.raw"] = { fg = p.green },
    ["@markup.link"] = s.url,
    ["@markup.link.url"] = s.url,
    ["@text.reference"] = s.url,
    ["@markup.list"] = { fg = p.orange },

    ["@diff.plus"] = { fg = p.diff_add_fg, bg = p.diff_add_bg },
    ["@diff.minus"] = { fg = p.diff_delete_fg, bg = p.diff_delete_bg },
    ["@diff.delta"] = { fg = p.diff_change_fg },

    ["@module"] = { fg = p.namespace },
    ["@namespace"] = { fg = p.namespace },

    ["@lsp.type.namespace"] = { fg = p.namespace },
    ["@lsp.type.module"] = { fg = p.namespace },
    ["@lsp.type.property"] = { fg = p.property },
    ["@lsp.type.interface"] = { fg = p.interface },
    ["@lsp.type.type"] = { fg = p.interface },
    ["@lsp.type.class"] = { fg = p.class },
    ["@lsp.type.component.vue"] = { fg = p.class },
    ["@lsp.type.enum"] = { fg = p.class },
    ["@lsp.type.struct"] = { fg = p.class },
    ["@lsp.type.function"] = { fg = p.entity },
    ["@lsp.type.method"] = { fg = p.entity },
    ["@lsp.type.macro"] = { fg = p.entity },
    ["@lsp.type.variable"] = { fg = p.variable },
    ["@lsp.type.parameter"] = { fg = p.variable },
    ["@lsp.type.decorator"] = { fg = p.attribute },
    ["@lsp.type.const"] = { fg = p.constant },
    ["@lsp.type.enumMember"] = { fg = p.constant },
  }
end

return M
