local M = {}

function M.get(p)
  return {
    Normal = { fg = p.fg, bg = p.bg },
    NormalNC = { fg = p.fg, bg = p.bg },
    NormalFloat = { fg = p.fg, bg = p.bg },
    FloatBorder = { fg = p.border, bg = p.bg },
    FloatTitle = { fg = p.fg, bg = p.bg, bold = true },
    ColorColumn = { bg = p.bg_alt },
    CursorLine = { bg = p.bg_alt },
    CursorColumn = { bg = p.bg_alt },
    CursorLineNr = { fg = p.fg_dim, bold = true },
    LineNr = { fg = p.subtle },
    Folded = { fg = p.muted, bg = p.bg_alt },
    FoldColumn = { fg = p.muted, bg = p.bg },
    SignColumn = { bg = p.bg },
    VertSplit = { fg = p.border, bg = p.bg },
    WinSeparator = { fg = p.border, bg = p.bg },
    Visual = { bg = p.selection },
    VisualNOS = { bg = p.inactive_selection },
    Search = { fg = p.bg, bg = p.yellow },
    IncSearch = { fg = p.bg, bg = p.orange },
    CurSearch = { fg = p.bg, bg = p.yellow },
    Substitute = { fg = p.bg, bg = p.orange },
    MatchParen = { fg = p.green, bg = p.bg_alt, bold = true },
    Pmenu = { fg = p.fg, bg = p.bg_alt },
    PmenuSel = { fg = p.fg, bg = p.selection },
    PmenuSbar = { bg = p.bg_alt },
    PmenuThumb = { bg = p.subtle },
    Question = { fg = p.green },
    MoreMsg = { fg = p.green },
    ModeMsg = { fg = p.fg_dim },
    NonText = { fg = p.subtle },
    EndOfBuffer = { fg = p.bg },
    SpecialKey = { fg = p.subtle },
    Whitespace = { fg = p.whitespace },
    StatusLine = { fg = p.fg_dim, bg = p.bg },
    StatusLineNC = { fg = p.subtle, bg = p.bg },
    TabLine = { fg = p.muted, bg = p.bg },
    TabLineFill = { bg = p.bg },
    TabLineSel = { fg = p.fg, bg = p.bg_alt, bold = true },

    Comment = { fg = p.comment, italic = true },
    Constant = { fg = p.constant },
    String = { fg = p.string },
    Character = { fg = p.string },
    Number = { fg = p.number },
    Boolean = { fg = p.boolean },
    Float = { fg = p.number },
    Identifier = { fg = p.variable },
    Function = { fg = p.entity },
    Statement = { fg = p.keyword, italic = true },
    Conditional = { fg = p.keyword, italic = true },
    Repeat = { fg = p.keyword, italic = true },
    Label = { fg = p.property },
    Operator = { fg = p.operator },
    Keyword = { fg = p.keyword, italic = true },
    Exception = { fg = p.red },
    PreProc = { fg = p.keyword, italic = true },
    Include = { fg = p.entity },
    Define = { fg = p.keyword, italic = true },
    Macro = { fg = p.magenta },
    Type = { fg = p.primitive },
    StorageClass = { fg = p.storage, italic = true },
    Structure = { fg = p.primitive },
    Special = { fg = p.support },
    SpecialChar = { fg = p.yellow },
    Delimiter = { fg = p.delimiter },
    Underlined = { fg = p.green, underline = true },
    Error = { fg = p.invalid },
    Todo = { fg = p.yellow, bg = p.bg_alt, bold = true },

    DiagnosticError = { fg = p.red },
    DiagnosticWarn = { fg = p.orange },
    DiagnosticInfo = { fg = p.blue },
    DiagnosticHint = { fg = p.green },
    DiagnosticUnderlineError = { sp = p.red, undercurl = true },
    DiagnosticUnderlineWarn = { sp = p.orange, undercurl = true },
    DiagnosticUnderlineInfo = { sp = p.blue, undercurl = true },
    DiagnosticUnderlineHint = { sp = p.green, undercurl = true },

    DiffAdd = { fg = p.diff_add_fg, bg = p.diff_add_bg },
    DiffChange = { fg = p.diff_change_fg, bg = p.diff_change_bg },
    DiffDelete = { fg = p.diff_delete_fg, bg = p.diff_delete_bg },
    DiffText = { fg = p.diff_header, bg = p.bg_alt },

    Directory = { fg = p.green },
    Title = { fg = p.green, bold = true },
    ErrorMsg = { fg = p.red },
    WarningMsg = { fg = p.orange },

    ["@comment"] = { link = "Comment" },
    ["@punctuation"] = { fg = p.delimiter },
    ["@punctuation.delimiter"] = { fg = p.delimiter },
    ["@punctuation.bracket"] = { fg = p.delimiter },
    ["@punctuation.special"] = { fg = p.delimiter },
    ["@operator"] = { fg = p.operator },

    ["@string"] = { link = "String" },
    ["@string.documentation"] = { fg = p.comment },
    ["@string.escape"] = { fg = p.yellow },
    ["@string.regexp"] = { fg = p.regexp },
    ["@string.special"] = { fg = p.string },
    ["@string.special.url"] = { fg = p.link, underline = true },

    ["@number"] = { link = "Number" },
    ["@number.float"] = { link = "Float" },
    ["@boolean"] = { link = "Boolean" },
    ["@constant"] = { link = "Constant" },
    ["@constant.builtin"] = { fg = p.storage },
    ["@constant.macro"] = { fg = p.constant },

    ["@variable"] = { fg = p.variable },
    ["@variable.builtin"] = { fg = p.constant },
    ["@variable.parameter"] = { fg = p.fg },
    ["@variable.member"] = { fg = p.property },
    ["@property"] = { fg = p.property },
    ["@field"] = { fg = p.property },

    ["@function"] = { fg = p.entity },
    ["@function.builtin"] = { fg = p.support },
    ["@function.call"] = { fg = p.entity },
    ["@function.macro"] = { fg = p.entity },
    ["@method"] = { fg = p.entity },
    ["@method.call"] = { fg = p.entity },
    ["@constructor"] = { fg = p.class },

    ["@keyword"] = { fg = p.keyword, italic = true },
    ["@keyword.function"] = { fg = p.keyword, italic = true },
    ["@keyword.operator"] = { fg = p.operator },
    ["@keyword.return"] = { fg = p.keyword, italic = true },
    ["@conditional"] = { link = "Conditional" },
    ["@repeat"] = { link = "Repeat" },
    ["@label"] = { link = "Label" },

    ["@type"] = { fg = p.primitive },
    ["@type.builtin"] = { fg = p.storage },
    ["@type.definition"] = { fg = p.primitive },
    ["@type.qualifier"] = { fg = p.storage, italic = true },

    ["@tag"] = { fg = p.tag },
    ["@tag.attribute"] = { fg = p.attribute },
    ["@tag.delimiter"] = { fg = p.delimiter },

    ["@markup.heading"] = { fg = p.green, bold = true },
    ["@markup.strong"] = { fg = p.fg, bold = true },
    ["@markup.italic"] = { fg = p.fg, italic = true },
    ["@markup.quote"] = { fg = p.interface },
    ["@markup.raw"] = { fg = p.green },
    ["@markup.link"] = { fg = p.string },
    ["@markup.link.url"] = { fg = p.link, underline = true },
    ["@markup.list"] = { fg = p.orange },

    ["@diff.plus"] = { fg = p.diff_add_fg },
    ["@diff.minus"] = { fg = p.diff_delete_fg },
    ["@diff.delta"] = { fg = p.diff_change_fg },

    ["@module"] = { fg = p.namespace },
    ["@namespace"] = { fg = p.namespace },

    ["@lsp.type.namespace"] = { fg = p.namespace },
    ["@lsp.type.module"] = { fg = p.namespace },
    ["@lsp.type.property"] = { fg = p.property },
    ["@lsp.type.interface"] = { fg = p.interface },
    ["@lsp.type.type"] = { fg = p.interface },
    ["@lsp.type.class"] = { fg = p.class },
    ["@lsp.type.enum"] = { fg = p.class },
    ["@lsp.type.struct"] = { fg = p.class },
    ["@lsp.type.function"] = { fg = p.entity },
    ["@lsp.type.method"] = { fg = p.entity },
    ["@lsp.type.macro"] = { fg = p.entity },
    ["@lsp.type.variable"] = { fg = p.variable },
    ["@lsp.type.parameter"] = { fg = p.fg },
    ["@lsp.type.decorator"] = { fg = p.attribute },
    ["@lsp.type.const"] = { fg = p.constant },
    ["@lsp.type.enumMember"] = { fg = p.constant },

    ["@lsp.typemod.variable.readonly"] = { fg = p.constant },
  }
end

return M
