local M = {}

function M.get(p)
  return {
    -- mini.nvim
    MiniStatuslineModeNormal = { fg = p.bg_dark, bg = p.green, bold = true },
    MiniStatuslineModeInsert = { fg = p.bg_dark, bg = p.blue, bold = true },
    MiniStatuslineModeVisual = { fg = p.bg_dark, bg = p.magenta, bold = true },
    MiniStatuslineModeReplace = { fg = p.bg_dark, bg = p.red, bold = true },
    MiniStatuslineModeCommand = { fg = p.bg_dark, bg = p.yellow, bold = true },
    MiniStatuslineModeOther = { fg = p.bg_dark, bg = p.cyan, bold = true },
    MiniStatuslineDevinfo = { fg = p.fg_dim, bg = p.bg_dark },
    MiniStatuslineFilename = { fg = p.fg, bg = p.bg_alt },
    MiniStatuslineFileinfo = { fg = p.fg_dim, bg = p.bg_dark },
    MiniStatuslineInactive = { fg = p.subtle, bg = p.bg_dark },
    MiniHipatternsFixme = { fg = p.bg, bg = p.red, bold = true },
    MiniHipatternsHack = { fg = p.bg, bg = p.orange, bold = true },
    MiniHipatternsNote = { fg = p.bg, bg = p.blue, bold = true },
    MiniHipatternsTodo = { fg = p.bg, bg = p.yellow, bold = true },
    MiniIconsAzure = { fg = p.blue },
    MiniIconsBlue = { fg = p.blue },
    MiniIconsCyan = { fg = p.cyan },
    MiniIconsGreen = { fg = p.green },
    MiniIconsGrey = { fg = p.muted },
    MiniIconsOrange = { fg = p.orange },
    MiniIconsPurple = { fg = p.magenta },
    MiniIconsRed = { fg = p.red },
    MiniIconsYellow = { fg = p.yellow },

    -- snacks.nvim shared windows
    SnacksNormal = { fg = p.fg, bg = p.bg },
    SnacksNormalNC = { fg = p.fg_dim, bg = p.bg },
    SnacksWinBar = { fg = p.fg, bg = p.bg_alt, bold = true },
    SnacksWinBarNC = { fg = p.muted, bg = p.bg_alt },
    SnacksTitle = { fg = p.green, bold = true },
    SnacksFooter = { fg = p.fg_dim },
    SnacksFooterKey = { fg = p.orange, bold = true },
    SnacksFooterDesc = { fg = p.muted },
    SnacksBackdrop = { bg = p.bg_dark },
    SnacksWinSeparator = { fg = p.border, bg = p.bg },
    SnacksWinKey = { fg = p.orange, bold = true },
    SnacksWinKeySep = { fg = p.subtle },
    SnacksWinKeyDesc = { fg = p.fg_dim },

    -- snacks.nvim picker / explorer
    SnacksPickerMatch = { fg = p.orange, bold = true },
    SnacksPickerSearch = { fg = p.bg, bg = p.yellow },
    SnacksPickerPrompt = { fg = p.green, bold = true },
    SnacksPickerInputSearch = { fg = p.yellow },
    SnacksPickerSpecial = { fg = p.support },
    SnacksPickerLabel = { fg = p.property },
    SnacksPickerTotals = { fg = p.muted },
    SnacksPickerFile = { fg = p.fg },
    SnacksPickerLink = { fg = p.link, underline = true },
    SnacksPickerLinkBroken = { fg = p.red, underline = true },
    SnacksPickerDirectory = { fg = p.green },
    SnacksPickerPathIgnored = { fg = p.subtle },
    SnacksPickerPathHidden = { fg = p.muted },
    SnacksPickerDir = { fg = p.green },
    SnacksPickerToggle = { fg = p.orange },
    SnacksPickerDimmed = { fg = p.subtle },
    SnacksPickerRow = { fg = p.number },
    SnacksPickerCol = { fg = p.number },
    SnacksPickerComment = { fg = p.comment, italic = true },
    SnacksPickerDesc = { fg = p.fg_dim },
    SnacksPickerDelim = { fg = p.delimiter },
    SnacksPickerSpinner = { fg = p.cyan },
    SnacksPickerSelected = { fg = p.green, bold = true },
    SnacksPickerCmd = { fg = p.entity },
    SnacksPickerCmdBuiltin = { fg = p.support },
    SnacksPickerUnselected = { fg = p.subtle },
    SnacksPickerIdx = { fg = p.muted },
    SnacksPickerBold = { fg = p.fg, bold = true },
    SnacksPickerTree = { fg = p.subtle },
    SnacksPickerItalic = { fg = p.fg_dim, italic = true },
    SnacksPickerCode = { fg = p.string },
    SnacksPickerAuPattern = { fg = p.string },
    SnacksPickerAuEvent = { fg = p.keyword, italic = true },
    SnacksPickerAuGroup = { fg = p.namespace },
    SnacksPickerDiagnosticCode = { fg = p.muted },
    SnacksPickerDiagnosticSource = { fg = p.comment },
    SnacksPickerRegister = { fg = p.orange },
    SnacksPickerKeymapMode = { fg = p.magenta },
    SnacksPickerKeymapLhs = { fg = p.green },
    SnacksPickerKeymapNowait = { fg = p.orange },
    SnacksPickerKeymapRhs = { fg = p.fg_dim },
    SnacksPickerBufNr = { fg = p.number },
    SnacksPickerBufFlags = { fg = p.orange },
    SnacksPickerBufType = { fg = p.interface },
    SnacksPickerFileType = { fg = p.primitive },
    SnacksPickerTime = { fg = p.muted },
    SnacksPickerUndoAdded = { fg = p.diff_add_fg },
    SnacksPickerUndoRemoved = { fg = p.diff_delete_fg },
    SnacksPickerUndoCurrent = { fg = p.yellow, bold = true },
    SnacksPickerUndoSaved = { fg = p.green },
    SnacksPickerGitCommit = { fg = p.yellow },
    SnacksPickerGitBreaking = { fg = p.red, bold = true },
    SnacksPickerGitDetached = { fg = p.orange },
    SnacksPickerGitBranch = { fg = p.green },
    SnacksPickerGitBranchCurrent = { fg = p.green, bold = true },
    SnacksPickerGitDate = { fg = p.muted },
    SnacksPickerGitIssue = { fg = p.blue },
    SnacksPickerGitAuthor = { fg = p.attribute },
    SnacksPickerGitType = { fg = p.magenta },
    SnacksPickerGitScope = { fg = p.namespace },
    SnacksPickerGitStatus = { fg = p.muted },
    SnacksPickerGitStatusAdded = { fg = p.diff_add_fg },
    SnacksPickerGitStatusModified = { fg = p.diff_change_fg },
    SnacksPickerGitStatusDeleted = { fg = p.diff_delete_fg },
    SnacksPickerGitStatusRenamed = { fg = p.blue },
    SnacksPickerGitStatusCopied = { fg = p.cyan },
    SnacksPickerGitStatusUntracked = { fg = p.orange },
    SnacksPickerGitStatusIgnored = { fg = p.subtle },
    SnacksPickerGitStatusUnmerged = { fg = p.red },
    SnacksPickerGitStatusStaged = { fg = p.green, bold = true },
    SnacksPickerManSection = { fg = p.magenta },
    SnacksPickerPickWin = { fg = p.bg, bg = p.yellow, bold = true },
    SnacksPickerPickWinCurrent = { fg = p.bg, bg = p.green, bold = true },
    SnacksPickerLspDisabled = { fg = p.subtle },
    SnacksPickerLspEnabled = { fg = p.green },
    SnacksPickerLspAttached = { fg = p.blue },
    SnacksPickerLspAttachedBuf = { fg = p.cyan },
    SnacksPickerLspUnavailable = { fg = p.red },
    SnacksPickerManPage = { fg = p.fg },
    SnacksPickerIcon = { fg = p.blue },
    SnacksPickerIconSource = { fg = p.muted },
    SnacksPickerIconName = { fg = p.fg },
    SnacksPickerIconCategory = { fg = p.magenta },
    SnacksPickerIconArray = { fg = p.orange },
    SnacksPickerIconBoolean = { fg = p.boolean },
    SnacksPickerIconClass = { fg = p.class },
    SnacksPickerIconConstant = { fg = p.constant },
    SnacksPickerIconConstructor = { fg = p.class },
    SnacksPickerIconEnum = { fg = p.class },
    SnacksPickerIconEnumMember = { fg = p.constant },
    SnacksPickerIconEvent = { fg = p.orange },
    SnacksPickerIconField = { fg = p.property },
    SnacksPickerIconFile = { fg = p.blue },
    SnacksPickerIconFunction = { fg = p.entity },
    SnacksPickerIconInterface = { fg = p.interface },
    SnacksPickerIconKey = { fg = p.property },
    SnacksPickerIconMethod = { fg = p.entity },
    SnacksPickerIconModule = { fg = p.namespace },
    SnacksPickerIconNamespace = { fg = p.namespace },
    SnacksPickerIconNull = { fg = p.muted },
    SnacksPickerIconNumber = { fg = p.number },
    SnacksPickerIconObject = { fg = p.primitive },
    SnacksPickerIconOperator = { fg = p.operator },
    SnacksPickerIconPackage = { fg = p.namespace },
    SnacksPickerIconProperty = { fg = p.property },
    SnacksPickerIconString = { fg = p.string },
    SnacksPickerIconStruct = { fg = p.class },
    SnacksPickerIconTypeParameter = { fg = p.primitive },
    SnacksPickerIconVariable = { fg = p.variable },
    SnacksPickerRule = { fg = p.border },

    -- snacks.nvim dashboard / notifier / input / indent / statuscolumn
    SnacksDashboardNormal = { fg = p.fg, bg = p.bg },
    SnacksDashboardTerminal = { fg = p.green },
    SnacksDashboardHeader = { fg = p.green, bold = true },
    SnacksDashboardFooter = { fg = p.fg_dim },
    SnacksDashboardIcon = { fg = p.blue },
    SnacksDashboardKey = { fg = p.orange, bold = true },
    SnacksDashboardDesc = { fg = p.fg_dim },
    SnacksNotifierInfo = { fg = p.blue },
    SnacksNotifierWarn = { fg = p.orange },
    SnacksNotifierError = { fg = p.red },
    SnacksNotifierDebug = { fg = p.magenta },
    SnacksNotifierTrace = { fg = p.muted },
    SnacksNotifierIconInfo = { fg = p.blue },
    SnacksNotifierIconWarn = { fg = p.orange },
    SnacksNotifierIconError = { fg = p.red },
    SnacksNotifierIconDebug = { fg = p.magenta },
    SnacksNotifierIconTrace = { fg = p.muted },
    SnacksNotifierBorderInfo = { fg = p.blue },
    SnacksNotifierBorderWarn = { fg = p.orange },
    SnacksNotifierBorderError = { fg = p.red },
    SnacksNotifierBorderDebug = { fg = p.magenta },
    SnacksNotifierBorderTrace = { fg = p.muted },
    SnacksNotifierTitleInfo = { fg = p.blue, bold = true },
    SnacksNotifierTitleWarn = { fg = p.orange, bold = true },
    SnacksNotifierTitleError = { fg = p.red, bold = true },
    SnacksNotifierTitleDebug = { fg = p.magenta, bold = true },
    SnacksNotifierTitleTrace = { fg = p.muted, bold = true },
    SnacksNotifierFooterInfo = { fg = p.blue },
    SnacksNotifierFooterWarn = { fg = p.orange },
    SnacksNotifierFooterError = { fg = p.red },
    SnacksNotifierFooterDebug = { fg = p.magenta },
    SnacksNotifierFooterTrace = { fg = p.muted },
    SnacksNotifierHistory = { fg = p.fg, bg = p.bg },
    SnacksNotifierHistoryTitle = { fg = p.green, bold = true },
    SnacksNotifierHistoryDateTime = { fg = p.muted },
    SnacksNotifierMinimal = { fg = p.fg, bg = p.bg },
    SnacksIndent = { fg = p.whitespace },
    SnacksIndentScope = { fg = p.yellow },
    SnacksIndentChunk = { fg = p.border },
    SnacksIndentBlank = { fg = p.bg_alt },
    SnacksIndent1 = { fg = p.red },
    SnacksIndent2 = { fg = p.orange },
    SnacksIndent3 = { fg = p.yellow },
    SnacksIndent4 = { fg = p.green },
    SnacksIndent5 = { fg = p.cyan },
    SnacksIndent6 = { fg = p.blue },
    SnacksIndent7 = { fg = p.magenta },
    SnacksIndent8 = { fg = p.muted },
    SnacksInputIcon = { fg = p.green },
    SnacksInputNormal = { fg = p.fg, bg = p.bg_alt },
    SnacksInputBorder = { fg = p.blue, bg = p.bg_alt },
    SnacksInputTitle = { fg = p.blue, bg = p.bg_alt, bold = true },
    SnacksInputPrompt = { fg = p.green },
    SnacksStatusColumnMark = { fg = p.yellow, bold = true },

    -- gitsigns.nvim
    GitSignsAdd = { fg = p.diff_add_fg },
    GitSignsChange = { fg = p.diff_change_fg },
    GitSignsDelete = { fg = p.diff_delete_fg },
    GitSignsChangedelete = { fg = p.diff_change_fg },
    GitSignsTopdelete = { fg = p.diff_delete_fg },
    GitSignsUntracked = { fg = p.orange },
    GitSignsAddNr = { fg = p.diff_add_fg },
    GitSignsChangeNr = { fg = p.diff_change_fg },
    GitSignsDeleteNr = { fg = p.diff_delete_fg },
    GitSignsChangedeleteNr = { fg = p.diff_change_fg },
    GitSignsTopdeleteNr = { fg = p.diff_delete_fg },
    GitSignsUntrackedNr = { fg = p.orange },
    GitSignsAddLn = { bg = p.diff_add_bg },
    GitSignsChangeLn = { bg = p.diff_change_bg },
    GitSignsChangedeleteLn = { bg = p.diff_change_bg },
    GitSignsTopdeleteLn = { bg = p.diff_delete_bg },
    GitSignsUntrackedLn = { bg = p.bg_alt },
    GitSignsAddCul = { fg = p.diff_add_fg, bg = p.bg_alt },
    GitSignsChangeCul = { fg = p.diff_change_fg, bg = p.bg_alt },
    GitSignsDeleteCul = { fg = p.diff_delete_fg, bg = p.bg_alt },
    GitSignsChangedeleteCul = { fg = p.diff_change_fg, bg = p.bg_alt },
    GitSignsTopdeleteCul = { fg = p.diff_delete_fg, bg = p.bg_alt },
    GitSignsUntrackedCul = { fg = p.orange, bg = p.bg_alt },
    GitSignsStagedAdd = { fg = p.green },
    GitSignsStagedChange = { fg = p.yellow },
    GitSignsStagedDelete = { fg = p.red },
    GitSignsStagedChangedelete = { fg = p.yellow },
    GitSignsStagedTopdelete = { fg = p.red },
    GitSignsStagedUntracked = { fg = p.orange },
    GitSignsAddPreview = { fg = p.diff_add_fg, bg = p.diff_add_bg },
    GitSignsDeletePreview = { fg = p.diff_delete_fg, bg = p.diff_delete_bg },
    GitSignsNoEOLPreview = { fg = p.orange },
    GitSignsAddInline = { bg = p.diff_add_bg },
    GitSignsDeleteInline = { bg = p.diff_delete_bg },
    GitSignsChangeInline = { bg = p.diff_change_bg },
    GitSignsAddLnInline = { bg = p.diff_add_bg },
    GitSignsChangeLnInline = { bg = p.diff_change_bg },
    GitSignsDeleteLnInline = { bg = p.diff_delete_bg },
    GitSignsDeleteVirtLn = { fg = p.diff_delete_fg, bg = p.diff_delete_bg },
    GitSignsDeleteVirtLnInLine = { fg = p.diff_delete_fg, bg = p.bg_alt },
    GitSignsVirtLnum = { fg = p.subtle },
    GitSignsCurrentLineBlame = { fg = p.subtle, italic = true },

    -- bufferline.nvim
    BufferLineFill = { bg = p.bg },
    BufferLineBackground = { fg = p.muted, bg = p.bg },
    BufferLineBuffer = { fg = p.muted, bg = p.bg },
    BufferLineBufferVisible = { fg = p.fg_dim, bg = p.bg },
    BufferLineBufferSelected = { fg = p.fg, bg = p.bg_alt, bold = true },
    BufferLineCloseButton = { fg = p.subtle, bg = p.bg },
    BufferLineCloseButtonVisible = { fg = p.muted, bg = p.bg },
    BufferLineCloseButtonSelected = { fg = p.red, bg = p.bg_alt },
    BufferLineNumbers = { fg = p.subtle, bg = p.bg },
    BufferLineNumbersVisible = { fg = p.muted, bg = p.bg },
    BufferLineNumbersSelected = { fg = p.fg_dim, bg = p.bg_alt, bold = true },
    BufferLineModified = { fg = p.orange, bg = p.bg },
    BufferLineModifiedVisible = { fg = p.orange, bg = p.bg },
    BufferLineModifiedSelected = { fg = p.orange, bg = p.bg_alt },
    BufferLineDuplicate = { fg = p.subtle, bg = p.bg, italic = true },
    BufferLineDuplicateVisible = { fg = p.muted, bg = p.bg, italic = true },
    BufferLineDuplicateSelected = { fg = p.fg_dim, bg = p.bg_alt, italic = true },
    BufferLineSeparator = { fg = p.border, bg = p.bg },
    BufferLineSeparatorVisible = { fg = p.border, bg = p.bg },
    BufferLineSeparatorSelected = { fg = p.border, bg = p.bg_alt },
    BufferLineIndicatorVisible = { fg = p.bg, bg = p.bg },
    BufferLineIndicatorSelected = { fg = p.green, bg = p.bg_alt },
    BufferLinePick = { fg = p.red, bg = p.bg, bold = true },
    BufferLinePickVisible = { fg = p.red, bg = p.bg, bold = true },
    BufferLinePickSelected = { fg = p.red, bg = p.bg_alt, bold = true },
    BufferLineOffsetSeparator = { fg = p.border, bg = p.bg },
    BufferLineTab = { fg = p.muted, bg = p.bg },
    BufferLineTabSelected = { fg = p.fg, bg = p.bg_alt, bold = true },
    BufferLineTabClose = { fg = p.red, bg = p.bg },
    BufferLineTabSeparator = { fg = p.border, bg = p.bg },
    BufferLineTabSeparatorSelected = { fg = p.border, bg = p.bg_alt },
    BufferLineDiagnostic = { fg = p.subtle, bg = p.bg },
    BufferLineDiagnosticVisible = { fg = p.muted, bg = p.bg },
    BufferLineDiagnosticSelected = { fg = p.fg_dim, bg = p.bg_alt },
    BufferLineHint = { fg = p.green, bg = p.bg },
    BufferLineHintVisible = { fg = p.green, bg = p.bg },
    BufferLineHintSelected = { fg = p.green, bg = p.bg_alt, bold = true },
    BufferLineHintDiagnostic = { fg = p.green, bg = p.bg },
    BufferLineHintDiagnosticVisible = { fg = p.green, bg = p.bg },
    BufferLineHintDiagnosticSelected = { fg = p.green, bg = p.bg_alt },
    BufferLineInfo = { fg = p.blue, bg = p.bg },
    BufferLineInfoVisible = { fg = p.blue, bg = p.bg },
    BufferLineInfoSelected = { fg = p.blue, bg = p.bg_alt, bold = true },
    BufferLineInfoDiagnostic = { fg = p.blue, bg = p.bg },
    BufferLineInfoDiagnosticVisible = { fg = p.blue, bg = p.bg },
    BufferLineInfoDiagnosticSelected = { fg = p.blue, bg = p.bg_alt },
    BufferLineWarning = { fg = p.orange, bg = p.bg },
    BufferLineWarningVisible = { fg = p.orange, bg = p.bg },
    BufferLineWarningSelected = { fg = p.orange, bg = p.bg_alt, bold = true },
    BufferLineWarningDiagnostic = { fg = p.orange, bg = p.bg },
    BufferLineWarningDiagnosticVisible = { fg = p.orange, bg = p.bg },
    BufferLineWarningDiagnosticSelected = { fg = p.orange, bg = p.bg_alt },
    BufferLineError = { fg = p.red, bg = p.bg },
    BufferLineErrorVisible = { fg = p.red, bg = p.bg },
    BufferLineErrorSelected = { fg = p.red, bg = p.bg_alt, bold = true },
    BufferLineErrorDiagnostic = { fg = p.red, bg = p.bg },
    BufferLineErrorDiagnosticVisible = { fg = p.red, bg = p.bg },
    BufferLineErrorDiagnosticSelected = { fg = p.red, bg = p.bg_alt },
    BufferLineGroupSeparator = { fg = p.border, bg = p.bg },
    BufferLineGroupLabel = { fg = p.green, bg = p.bg_alt, bold = true },
    BufferLineTruncMarker = { fg = p.subtle, bg = p.bg },
    BufferLineMiniIconsAzure = { fg = p.blue, bg = p.bg },
    BufferLineMiniIconsAzureInactive = { fg = p.blue, bg = p.bg },
    BufferLineMiniIconsAzureSelected = { fg = p.blue, bg = p.bg_alt },
    BufferLineMiniIconsBlue = { fg = p.blue, bg = p.bg },
    BufferLineMiniIconsBlueInactive = { fg = p.blue, bg = p.bg },
    BufferLineMiniIconsBlueSelected = { fg = p.blue, bg = p.bg_alt },
    BufferLineMiniIconsCyan = { fg = p.cyan, bg = p.bg },
    BufferLineMiniIconsCyanInactive = { fg = p.cyan, bg = p.bg },
    BufferLineMiniIconsCyanSelected = { fg = p.cyan, bg = p.bg_alt },
    BufferLineMiniIconsGreen = { fg = p.green, bg = p.bg },
    BufferLineMiniIconsGreenInactive = { fg = p.green, bg = p.bg },
    BufferLineMiniIconsGreenSelected = { fg = p.green, bg = p.bg_alt },
    BufferLineMiniIconsGrey = { fg = p.muted, bg = p.bg },
    BufferLineMiniIconsGreyInactive = { fg = p.muted, bg = p.bg },
    BufferLineMiniIconsGreySelected = { fg = p.muted, bg = p.bg_alt },
    BufferLineMiniIconsOrange = { fg = p.orange, bg = p.bg },
    BufferLineMiniIconsOrangeInactive = { fg = p.orange, bg = p.bg },
    BufferLineMiniIconsOrangeSelected = { fg = p.orange, bg = p.bg_alt },
    BufferLineMiniIconsPurple = { fg = p.magenta, bg = p.bg },
    BufferLineMiniIconsPurpleInactive = { fg = p.magenta, bg = p.bg },
    BufferLineMiniIconsPurpleSelected = { fg = p.magenta, bg = p.bg_alt },
    BufferLineMiniIconsRed = { fg = p.red, bg = p.bg },
    BufferLineMiniIconsRedInactive = { fg = p.red, bg = p.bg },
    BufferLineMiniIconsRedSelected = { fg = p.red, bg = p.bg_alt },
    BufferLineMiniIconsYellow = { fg = p.yellow, bg = p.bg },
    BufferLineMiniIconsYellowInactive = { fg = p.yellow, bg = p.bg },
    BufferLineMiniIconsYellowSelected = { fg = p.yellow, bg = p.bg_alt },

    -- blink.cmp
    BlinkCmpLabel = { fg = p.fg },
    BlinkCmpLabelMatch = { fg = p.orange, bold = true },
    BlinkCmpLabelDeprecated = { fg = p.subtle, strikethrough = true },
    BlinkCmpLabelDetail = { fg = p.muted },
    BlinkCmpLabelDescription = { fg = p.comment },
    BlinkCmpSource = { fg = p.muted },
    BlinkCmpKind = { fg = p.blue },
    BlinkCmpKindText = { fg = p.fg },
    BlinkCmpKindMethod = { fg = p.entity },
    BlinkCmpKindFunction = { fg = p.entity },
    BlinkCmpKindConstructor = { fg = p.class },
    BlinkCmpKindField = { fg = p.property },
    BlinkCmpKindVariable = { fg = p.variable },
    BlinkCmpKindClass = { fg = p.class },
    BlinkCmpKindInterface = { fg = p.interface },
    BlinkCmpKindModule = { fg = p.namespace },
    BlinkCmpKindProperty = { fg = p.property },
    BlinkCmpKindUnit = { fg = p.number },
    BlinkCmpKindValue = { fg = p.constant },
    BlinkCmpKindEnum = { fg = p.class },
    BlinkCmpKindKeyword = { fg = p.keyword, italic = true },
    BlinkCmpKindSnippet = { fg = p.magenta },
    BlinkCmpKindColor = { fg = p.cyan },
    BlinkCmpKindFile = { fg = p.blue },
    BlinkCmpKindReference = { fg = p.link },
    BlinkCmpKindFolder = { fg = p.green },
    BlinkCmpKindEnumMember = { fg = p.constant },
    BlinkCmpKindConstant = { fg = p.constant },
    BlinkCmpKindStruct = { fg = p.class },
    BlinkCmpKindEvent = { fg = p.orange },
    BlinkCmpKindOperator = { fg = p.operator },
    BlinkCmpKindTypeParameter = { fg = p.primitive },
    BlinkCmpScrollBarThumb = { bg = p.subtle },
    BlinkCmpScrollBarGutter = { bg = p.bg_alt },
    BlinkCmpGhostText = { fg = p.subtle },
    BlinkCmpMenu = { fg = p.fg, bg = p.bg_alt },
    BlinkCmpMenuBorder = { fg = p.border, bg = p.bg_alt },
    BlinkCmpMenuSelection = { fg = p.fg, bg = p.selection },
    BlinkCmpDoc = { fg = p.fg, bg = p.bg },
    BlinkCmpDocBorder = { fg = p.border, bg = p.bg },
    BlinkCmpDocSeparator = { fg = p.border, bg = p.bg },
    BlinkCmpDocCursorLine = { bg = p.bg_alt },
    BlinkCmpSignatureHelp = { fg = p.fg, bg = p.bg },
    BlinkCmpSignatureHelpBorder = { fg = p.border, bg = p.bg },
    BlinkCmpSignatureHelpActiveParameter = { fg = p.orange, bold = true },

    -- noice.nvim
    NoiceCmdline = { fg = p.fg, bg = p.bg_dark },
    NoiceCmdlineIcon = { fg = p.blue },
    NoiceCmdlineIconSearch = { fg = p.yellow },
    NoiceCmdlinePrompt = { fg = p.green, bold = true },
    NoiceCmdlinePopup = { fg = p.fg, bg = p.bg_alt },
    NoiceCmdlinePopupBorder = { fg = p.blue, bg = p.bg_alt },
    NoiceCmdlinePopupTitle = { fg = p.blue, bg = p.bg_alt, bold = true },
    NoiceCmdlinePopupBorderSearch = { fg = p.yellow, bg = p.bg_alt },
    NoiceConfirm = { fg = p.fg, bg = p.bg_alt },
    NoiceConfirmBorder = { fg = p.blue, bg = p.bg_alt },
    NoiceCursor = { fg = p.bg, bg = p.fg },
    NoiceMini = { fg = p.fg_dim, bg = p.bg_dark },
    NoicePopup = { fg = p.fg, bg = p.bg },
    NoicePopupBorder = { fg = p.border, bg = p.bg },
    NoicePopupmenu = { fg = p.fg, bg = p.bg_alt },
    NoicePopupmenuBorder = { fg = p.border, bg = p.bg_alt },
    NoicePopupmenuMatch = { fg = p.orange, bold = true },
    NoicePopupmenuSelected = { fg = p.fg, bg = p.selection },
    NoiceScrollbar = { bg = p.bg_alt },
    NoiceScrollbarThumb = { bg = p.subtle },
    NoiceSplit = { fg = p.fg, bg = p.bg },
    NoiceSplitBorder = { fg = p.border, bg = p.bg },
    NoiceVirtualText = { fg = p.blue },
    NoiceFormatProgressDone = { fg = p.green, bg = p.bg_alt },
    NoiceFormatProgressTodo = { fg = p.subtle, bg = p.bg_alt },
    NoiceFormatEvent = { fg = p.magenta },
    NoiceFormatKind = { fg = p.orange },
    NoiceFormatDate = { fg = p.muted },
    NoiceFormatConfirm = { fg = p.green },
    NoiceFormatConfirmDefault = { fg = p.green, bold = true },
    NoiceFormatTitle = { fg = p.green, bold = true },
    NoiceFormatLevelDebug = { fg = p.magenta },
    NoiceFormatLevelTrace = { fg = p.muted },
    NoiceFormatLevelOff = { fg = p.subtle },
    NoiceFormatLevelInfo = { fg = p.blue },
    NoiceFormatLevelWarn = { fg = p.orange },
    NoiceFormatLevelError = { fg = p.red },
    NoiceLspProgressSpinner = { fg = p.cyan },
    NoiceLspProgressTitle = { fg = p.fg },
    NoiceLspProgressClient = { fg = p.muted },
    NoiceCompletionItemMenu = { fg = p.muted },
    NoiceCompletionItemWord = { fg = p.fg },
    NoiceCompletionItemKindDefault = { fg = p.blue },
    NoiceCompletionItemKindColor = { fg = p.cyan },
    NoiceCompletionItemKindFunction = { fg = p.entity },
    NoiceCompletionItemKindClass = { fg = p.class },
    NoiceCompletionItemKindMethod = { fg = p.entity },
    NoiceCompletionItemKindConstructor = { fg = p.class },
    NoiceCompletionItemKindInterface = { fg = p.interface },
    NoiceCompletionItemKindModule = { fg = p.namespace },
    NoiceCompletionItemKindStruct = { fg = p.class },
    NoiceCompletionItemKindKeyword = { fg = p.keyword, italic = true },
    NoiceCompletionItemKindValue = { fg = p.constant },
    NoiceCompletionItemKindProperty = { fg = p.property },
    NoiceCompletionItemKindConstant = { fg = p.constant },
    NoiceCompletionItemKindSnippet = { fg = p.magenta },
    NoiceCompletionItemKindFolder = { fg = p.green },
    NoiceCompletionItemKindText = { fg = p.fg },
    NoiceCompletionItemKindEnumMember = { fg = p.constant },
    NoiceCompletionItemKindUnit = { fg = p.number },
    NoiceCompletionItemKindField = { fg = p.property },
    NoiceCompletionItemKindFile = { fg = p.blue },
    NoiceCompletionItemKindVariable = { fg = p.variable },
    NoiceCompletionItemKindEnum = { fg = p.class },
    NoiceHiddenCursor = { blend = 100, nocombine = true },

    -- nvim-treesitter-context / rainbow-delimiters.nvim
    TreesitterContext = { bg = p.bg_alt },
    TreesitterContextLineNumber = { fg = p.subtle, bg = p.bg_alt },
    TreesitterContextLineNumberBottom = { fg = p.fg_dim, bg = p.bg_alt, underline = true },
    TreesitterContextSeparator = { fg = p.border, bg = p.bg },
    TreesitterContextBottom = { sp = p.border, underline = true },
    RainbowDelimiterRed = { fg = p.red },
    RainbowDelimiterYellow = { fg = p.yellow },
    RainbowDelimiterBlue = { fg = p.blue },
    RainbowDelimiterOrange = { fg = p.orange },
    RainbowDelimiterGreen = { fg = p.green },
    RainbowDelimiterViolet = { fg = p.magenta },
    RainbowDelimiterCyan = { fg = p.cyan },

    -- opencode.nvim
    OpencodeContextPlaceholder = { fg = p.muted, italic = true },
    OpencodeContextValue = { fg = p.string },
    OpencodeAgent = { fg = p.property, bold = true },
  }
end

return M
