return {
  "saghen/blink.cmp",
  version = "1.*",
  event = "InsertEnter",
  opts = {
    appearance = {
      kind_icons = {
        Text = "",
        Method = "",
        Function = "",
        Constructor = "",
        Field = "",
        Variable = "",
        Property = "",
        Class = "",
        Interface = "",
        Struct = "",
        Module = "",
        Unit = "",
        Value = "",
        Enum = "",
        EnumMember = "",
        Keyword = "",
        Constant = "",
        Snippet = "",
        Color = "",
        File = "",
        Reference = "",
        Folder = "",
        Event = "",
        Operator = "",
        TypeParameter = "",
      },
    },
    keymap = {
      preset = "super-tab",
      ["<C-Space>"] = { "show", "show_documentation", "hide_documentation" },
      ["<C-j>"] = { "select_next", "fallback_to_mappings" },
      ["<C-k>"] = { "select_prev", "fallback_to_mappings" },
    },
    completion = {
      documentation = {
        auto_show = true,
        auto_show_delay_ms = 250,
      },
    },
  },
}
